added sysctl zram parameters

diff --git a/scripts/various/install_arch_base b/scripts/various/install_arch_base
--- a/scripts/various/install_arch_base
+++ b/scripts/various/install_arch_base
@@ -2,7 +2,7 @@
 
 # Author: Barret E <https://github.com/archusXIV/>
 # Creation date: 2025-05-25
-# Script name: install_arch version 1.1.2
+# Script name: install_arch_base version 1.1.2
 # License: GPLv2
 #
 # This script automates the installation of Arch Linux with the following features:
@@ -23,7 +23,7 @@ r=$'\e[31m'
 g=$'\e[32m'
 c=$'\e[0m'
 
-# Display usage information if no arguments provided
+# Display usage information if no arguments are provided
 if [[ $# -eq 0 ]]; then
     echo ""
     cat <<'USAGE'
@@ -65,7 +65,7 @@ while getopts "c:D:f:h:k:K:l:r:R:s:S:x:t:" opt; do
     case $opt in
         c) country="$OPTARG" ;;
         D)
-            echo -e " \n${g}Available disks:\n${c}"
+            echo -e "\n ${g}Available disks:\n${c}"
             lsblk -I 8 -d -o NAME,SIZE,MODEL
             echo ""
             exit 0
@@ -82,7 +82,7 @@ while getopts "c:D:f:h:k:K:l:r:R:s:S:x:t:" opt; do
         t) timezone="${OPTARG}" ;;
         x) swap_size="${OPTARG}" ;;
         \?)
-            echo "${r}Invalid option -${OPTARG}${c}" >&2
+            echo " ${r}Invalid option -${OPTARG}${c}" >&2
             exit 1
         ;;
     esac
@@ -233,7 +233,7 @@ installBaseSystem() {
     reflector \
         --verbose \
         --country "${country}" \
-        --latest 10 \
+        --latest 20 \
         --age 24 \
         --protocol https \
         --sort rate \
@@ -292,7 +292,7 @@ echo "$hostname" > /etc/hostname
 echo "127.0.1.1        $hostname.localdomain    $hostname" >> /etc/hosts
 
 echo "KEYMAP=$keyboard_layout" > /etc/vconsole.conf
-echo "FONT=sun12x22" >> /etc/vconsole.conf
+echo "FONT=eurlatgr" >> /etc/vconsole.conf
 
 echo "Adding performance tweaks..."
 # Enable parallel module loading
@@ -300,7 +300,7 @@ sed -i 's/^MODULES=()/MODULES=(sd_mod ahci)/' /etc/mkinitcpio.conf
 sed -i 's/^#MODULES_DECOMPRESS="no"/MODULES_DECOMPRESS="yes"/' /etc/mkinitcpio.conf
 mkinitcpio -P
 
-systemctl enable NetworkManager
+systemctl enable NetworkManager.service
 
 echo "Set the root password:"
 passwd
@@ -317,9 +317,16 @@ EOL
 if [[ $is_uefi -eq 0 ]]; then
     cat > /etc/systemd/zram-generator.conf <<EOZ
 [zram0]
-zram-size = min (ram /2, ram)
+zram-size = min(ram /2, ram)
 compression-algorithm = zstd
 EOZ
+
+    cat > /etc/sysctl.d/99-zram-parameters.conf <<EOS
+vm.swappiness = 180
+vm.watermark_boost_factor = 0
+vm.watermark_scale_factor = 125
+vm.page-cluster = 0
+EOS
 
 # Grub stuff
 mkdir --parents /etc/pacman.d/hooks
@@ -338,7 +345,7 @@ Exec=/usr/bin/grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootl
 EOG
 else
     [[ -z "$root_disk" || ! -b /dev/"$root_disk" ]] && {
-        echo "${r}Error: Invalid or unset system disk for BIOS bootloader installation.${c}"
+        echo " ${r}Error: Invalid or unset system disk for BIOS bootloader installation.${c}"
         exit 1
     }
     cat > /etc/pacman.d/hooks/update_grub.hook <<EOB
@@ -378,24 +385,24 @@ exit
 EOF
     chmod +x /mnt/root/configure.sh
     if ! arch-chroot /mnt /root/configure.sh /dev/"$root_disk"; then
-        echo "${r}Error: Configuration script failed. Retaining /mnt/root/configure.sh for debugging.${c}"
+        echo " ${r}Error: Configuration script failed. Retaining /mnt/root/configure.sh for debugging.${c}"
     else
         rm /mnt/root/configure.sh
     fi
 }
 
 # We start from here
-echo -e "\nStarting Arch Linux installation...\n"
+echo -e "\n Starting Arch Linux installation...\n"
 
 # Verify we're in the live environment
 if [[ ! -f /run/archiso/bootmnt/arch/boot/x86_64/vmlinuz-linux ]]; then
-    echo "${r}This script must be run from the Arch Linux live environment!${c}"
+    echo " ${r}This script must be run from the Arch Linux live environment!${c}"
     exit 1
 fi
 
 # Check internet connectivity
 ping -c 1 archlinux.org >/dev/null 2>&1 || {
-    echo "${r}No internet connection! Please connect to the internet first.${c}"
+    echo " ${r}No internet connection! Please connect to the internet first.${c}"
     exit 1
 }
 
@@ -404,35 +411,35 @@ checkUefi
 is_uefi=$?
 
 # Confirm installation
-echo "${r}WARNING: This will erase ALL data on $root_disk${c}"
+echo "${r} WARNING: This will erase ALL data on $root_disk${c}"
 read -rp "Do you want to continue? (y/N) " confirm
 [[ ! $confirm =~ ^[Yy]$ ]] && {
-    echo "${r}Installation cancelled.${c}"
+    echo " ${r}Installation cancelled.${c}"
     exit 1
 }
 
 # Perform disks operations
 if [[ -n $home_disk ]]; then
-    echo "${g}Partitioning disks...${c}"
+    echo " ${g}Partitioning disks...${c}"
     partitionDisk "$is_uefi" "$root_disk" "$home_disk"
-    echo "${g}Setting up partitions...${c}"
+    echo " ${g}Setting up partitions...${c}"
     setupPartitions "$root_disk" "$is_uefi" "$home_disk"
 else
-    echo "${g}Formatting disk...${c}"
+    echo " ${g}Formatting disk...${c}"
     partitionDisk "$is_uefi" "$root_disk"
-    echo "${g}Setting up partitions...${c}"
+    echo " ${g}Setting up partitions...${c}"
     setupPartitions "$root_disk" "$is_uefi"
 fi
 
-echo "${g}Installing base system...${c}"
+echo " ${g}Installing base system...${c}"
 installBaseSystem
 
-echo "${g}Configuring system...${c}"
+echo " ${g}Configuring system...${c}"
 configureSystem "$is_uefi" "$root_disk"
 
-echo "${g}Unmounting partitions...${c}"
+echo " ${g}Unmounting partitions...${c}"
 umount -R /mnt
 
-echo -e "\n${g}Installation complete!${c}"
+echo -e "\n ${g}Installation complete!${c}"
 echo "You can now reboot into your new Arch Linux system."
 echo "After reboot, log in as root with the password you set."
