Update install_artix_base

diff --git a/scripts/various/install_artix_base b/scripts/various/install_artix_base
--- a/scripts/various/install_artix_base
+++ b/scripts/various/install_artix_base
@@ -2,17 +2,17 @@
 
 # Author: Barret E <https://github.com/archusXIV/>
 # Creation date: 2025-07-03
-# Script name: install_artix_base version 1.0.2
+# Script name: install_artix_base openrc version 1.1.0
 # License: GPLv2
 #
 # This script automates the installation of Artix Linux with the following features:
 # - Important: It must be run from an Artix Linux iso image!!!
 # - Supports both UEFI and BIOS systems, btrfs, xfs and ext4 file systems.
 # - For btrfs file system you will have the create your subvolumes yourself.
-# - Configurable disk partitioning with option for separate /home partition.
+# - Configurable disk partitioning with option for separate /home partition using cfdisk.
 # - Customizable keyboard layout, locale, timezone and hostname.
 # - Automatic mirror selection based on response rate and package database update.
-# - Installation of base system packages (minimal) and bootloader.
+# - Installation of base system packages (minimal) and bootloader (grub).
 # - Network configuration via NetworkManager.
 # - Root password setup during installation.
 # - Safety checks for live environment and internet connectivity.
@@ -29,56 +29,71 @@ if [[ $# -eq 0 ]]; then
     cat <<'USAGE'
              Artix Linux Installation Script by archusXIV
     ==============================================================
-    IMPORTANT! PARTITION TABLE LAYOUT:
-    UEFI MODE: EFI, (SWAP), ROOT, (HOME)
-    BIOS MODE: (SWAP), ROOT do not forget to mark it *bootable, (HOME)
 
     Available options:
-    -d all               List all present disks for decision making
+    -c <country>         Set your actual location (default: United States)
+    -D all               List all present disks for decision making
     -f <filesystem type> Set the filesystem type (ext4, btrfs, xfs, default: ext4)
-    -h <name>            Set hostname (default: artix)
+    -h <name>            Set hostname (default: archlinux)
     -k <kbd layout>      Set your keyboard layout (default: us)
     -l <locales>         Set system locales (default: en_US)
     -r <root disk>       Set the system disk (default: sda)
+    -R <root size>       Set the system disk size in GB (default: 30)
     -s <home disk>       Set the home disk for /home (optional: sdX)
+    -S <home size>       Set the home disk size in GB (uses remaining space if not set)
+    -x <swap size>       Set the swap size in GB for BIOS install (default: 4)
     -t <Region/Capital>  Set timezone (default: UTC)
 
-    Example usage:
-    ./install_artix_base -f btrfs -r sda -s sdb -k fr -l fr_FR -t Europe/Paris -h myartix
+    Example usage for UEFI install (no swap):
+    (root drive,root size,home drive,home size,country,keyboard,locales,timezone,hostname)
+
+    ./install_arch -r sda -R 40 -s sdb -S 100 -f btrfs -c France -k fr -l fr_FR -t Europe/Paris -h myarchuefi
+
+    Example usage for BIOS install (with swap size):
+    (root drive,swap size,home drive,country,keyboard,locales,timezone,hostname)
+
+    ./install_arch -r sda -x 4 -s sdb -f ext4 -c France -k fr -l fr_FR -t Europe/Paris -h myarchbios
 
 USAGE
     exit 1
 fi
 
 # Parse command line arguments
-while getopts "d:f:h:k:l:r:s:t:" opt; do
+while getopts "c:D:f:h:k:l:r:R:s:S:x:t:" opt; do
     case $opt in
-        d)
+        c) country="$OPTARG" ;;
+        D)
             echo -e " \n${g}Available disks:\n${c}"
             lsblk -I 8 -d -o NAME,SIZE,MODEL
             echo ""
             exit 0
         ;;
         f) fs_type="${OPTARG}" ;;
-        h) hostname="$OPTARG" ;;
-        k) keyboard_layout="$OPTARG" ;;
-        l) locale="$OPTARG" ;;
-        r) root_disk="$OPTARG" ;;
-        s) home_disk="$OPTARG" ;;
-        t) timezone="$OPTARG" ;;
+        h) hostname="${OPTARG}" ;;
+        k) keyboard_layout="${OPTARG}" ;;
+        l) locale="${OPTARG}" ;;
+        r) root_disk="${OPTARG}" ;;
+        R) root_size="${OPTARG}" ;;
+        s) home_disk="${OPTARG}" ;;
+        S) home_size="${OPTARG}" ;;
+        t) timezone="${OPTARG}" ;;
+        x) swap_size="${OPTARG}" ;;
         \?)
-            echo "${r}Invalid option -$OPTARG${c}" >&2
+            echo "${r}Invalid option -${OPTARG}${c}" >&2
             exit 1
         ;;
     esac
 done
 
 # Set defaults if not given
+country=${country:-"United States"}
 fs_type=${fs_type:-ext4}
-hostname=${hostname:-artix}
+hostname=${hostname:-archlinux}
 keyboard_layout=${keyboard_layout:-us}
 locale=${locale:-en_US}
 root_disk=${root_disk:-sda}
+root_size=${root_size:-30}
+swap_size=${swap_size:-4}
 timezone=${timezone:-UTC}
 
 checkUefi() {
@@ -114,15 +129,50 @@ errorDisk() {
     exit 1
 }
 
-createPartitionsTable() {
-    case "$1" in
-        --first-drive)
-            cfdisk /dev/"$root_disk"
-        ;;
-        --second-drive)
-            cfdisk /dev/"$home_disk"
-        ;;
-    esac
+partitionDisk() {
+    local is_uefi="$1"
+    local root_disk="$2"
+    local home_disk="$3"
+
+    ensureDisksPathsAreCorrect
+
+    # Verify disks exist and clear partition tables
+    for d in "$root_disk" ${home_disk:+"$home_disk"}; do
+        [[ ! -b $d ]] && errorDisk "disk_not_exist"
+        sgdisk -Z "$d" || errorDisk "clear_partition"
+    done
+
+    if [[ $is_uefi -eq 0 ]]; then
+        sgdisk -n 1:0:+512M -t 1:ef00 -c 1:"EFI System" "$root_disk" \
+        || errorDisk "create_efi"
+        sgdisk -n 2:0:+"${swap_size}"G -t 2:8200 -c 2:"Linux swap" "$root_disk" \
+        || errorDisk "create_swap"
+        sgdisk -n 3:0:+"${root_size}"G -t 2:8300 -c 3:"Linux root" "$root_disk" \
+        || errorDisk "create_root"
+    else
+        # BIOS partitioning
+        sgdisk -n 1:0:+1M -t 1:ef02 -c 1:"BIOS boot partition" "$root_disk" \
+        || errorDisk "create_bios_boot"
+        sgdisk -n 2:0:+"${swap_size}"G -t 2:8200 -c 2:"Linux swap" "$root_disk" \
+        || errorDisk "create_swap"
+        sgdisk -n 3:0:+"${root_size}"G -t 3:8300 -c 3:"Linux root" "$root_disk" \
+        || errorDisk "create_root"
+    fi
+
+    [[ -n $home_disk ]] && {
+        if [[ -n $home_size ]]; then
+            sgdisk -n 1:0:+"${home_size}"G -t 1:8300 -c 1:"Linux home" "$home_disk" \
+            || errorDisk "create_home"
+        else
+            sgdisk -n 1:0:0 -t 1:8300 -c 1:"Linux home" "$home_disk" \
+            || errorDisk "create_home"
+        fi
+    }
+
+    echo "${g}Debug: Refreshing partition table...${c}"
+    partprobe "$root_disk"
+    [[ -n $home_disk ]] && partprobe "$home_disk"
+    sleep 2 # Give the kernel some time to process
 }
 
 setupPartitions() {
@@ -176,13 +226,6 @@ setupPartitions() {
 }
 
 installBaseSystem() {
-    # Ensure the system clock is synchronized
-    rc-service ntpd start
-    pacman -Syy artix-keyring pacman-contrib --noconfirm
-    cp -f /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist_bkp
-    echo " ${g}Ranking mirrolist...be patient${c}"
-    rankmirrors -n 10 /etc/pacman.d/mirrorlist_bkp > /etc/pacman.d/mirrorlist
-    pacman -Syy
 
     declare -a EXTRA=()
     [[ $is_uefi -eq 0 ]] && EXTRA+=("efibootmgr")
@@ -194,12 +237,14 @@ installBaseSystem() {
         artix-branding-base \
         base \
         base-devel \
+        dosfstools \
         ${EXTRA[@]} \
         elogind-openrc \
         less \
         linux \
         linux-headers \
         linux-firmware \
+        networkmanager \
         networkmanager-openrc \
         openrc \
         pacman-contrib \
@@ -245,7 +290,6 @@ sed -i 's/^MODULES=()/MODULES=(sd_mod ahci)/' /etc/mkinitcpio.conf
 sed -i 's/^#MODULES_DECOMPRESS="no"/MODULES_DECOMPRESS="yes"/' /etc/mkinitcpio.conf
 mkinitcpio -P
 
-pacman -S --noconfirm networkmanager
 rc-update add NetworkManager default
 
 echo "Set the root password:"
@@ -344,20 +388,22 @@ read -rp "Do you want to continue? (y/N) " confirm
     exit 1
 }
 
+rc-service ntpd start
+pacman-key --init && pacman-key --populate artix
+pacman -Syy artix-keyring pacman-contrib gdisk --noconfirm
+cp -f /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist_bkp
+echo " ${g}Ranking mirrolist...be patient${c}"
+rankmirrors -n 10 /etc/pacman.d/mirrorlist_bkp > /etc/pacman.d/mirrorlist
+
 # Perform disks operations
 if [[ -n $home_disk ]]; then
-    echo "${g}Please setup partitions on /dev/$root_disk...${c}"
-    sleep 2
-    createPartitionsTable --first-drive
-    echo "${g}Please setup partitions on /dev/$home_disk...${c}"
-    sleep 2
-    createPartitionsTable --second-drive
+    echo "${g}Partitioning disks...${c}"
+    partitionDisk "$is_uefi" "$root_disk" "$home_disk"
     echo "${g}Setting up partitions...${c}"
     setupPartitions "$root_disk" "$is_uefi" "$home_disk"
 else
-    echo "${g}Please setup partitions on $root_disk...${c}"
-    sleep 2
-    createPartitionsTable --first-drive
+    echo "${g}Formatting disk...${c}"
+    partitionDisk "$is_uefi" "$root_disk"
     echo "${g}Setting up partitions...${c}"
     setupPartitions "$root_disk" "$is_uefi"
 fi
@@ -372,5 +418,5 @@ echo "${g}Unmounting partitions...${c}"
 umount -R /mnt
 
 echo -e "\n${g}Installation complete!${c}"
-echo "You can now reboot into your new Artix Linux system."
+echo "You can now reboot into your new Arch Linux system."
 echo "After reboot, log in as root with the password you set."
