added pacman test for extra packages

diff --git a/scripts/various/install_archlinux_Xdesktop b/scripts/various/install_archlinux_Xdesktop
--- a/scripts/various/install_archlinux_Xdesktop
+++ b/scripts/various/install_archlinux_Xdesktop
@@ -79,6 +79,13 @@ else
     extra_packages+=("htop")
 fi
 
+for pkg in "${extra_packages[@]}"; do
+    pacman -Ss "${pkg}" >/dev/null || {
+        echo "${r}${pkg} not found...exiting.${c}"
+        exit 1
+    }
+done
+
 echo ""
 read -rp " ${g}Do you want to add a user account now? [Y/n]: ${c}" add_account
 
diff --git a/scripts/various/install_artix_Xdesktop b/scripts/various/install_artix_Xdesktop
--- a/scripts/various/install_artix_Xdesktop
+++ b/scripts/various/install_artix_Xdesktop
@@ -78,6 +78,13 @@ else
     extra_packages+=("htop")
 fi
 
+for pkg in "${extra_packages[@]}"; do
+    pacman -Ss "${pkg}" >/dev/null || {
+        echo "${r}${pkg} not found...exiting.${c}"
+        exit 1
+    }
+done
+
 echo ""
 read -rp " ${g}Do you want to add a user now? [Y/n]: ${c}" create_user
 
