Update install_arch

diff --git a/scripts/various/install_arch b/scripts/various/install_arch
--- a/scripts/various/install_arch
+++ b/scripts/various/install_arch
@@ -95,6 +95,7 @@ errorDisk() {
     case "$1" in
         "clear_partition") echo "${r}Error: Failed to clear partition table${c}" ;;
         "create_efi") echo "${r}Error: Failed to create EFI partition${c}" ;;
+        "create_bios_boot") echo "${r}Error: Failed to create BIOS boot partition${c}" ;;
         "create_efi_mount") echo "${r}Error: Failed to create EFI mount point${c}" ;;
         "create_root") echo "${r}Error: Failed to create root partition${c}" ;;
         "create_home") echo "${r}Error: Failed to create home partition${c}" ;;
@@ -131,12 +132,21 @@ partitionDisk() {
         || errorDisk "create_efi"
     else
         # BIOS partitioning
-        sgdisk -n 1:0:+"$swap_size"G -t 1:8200 -c 1:"Linux swap" "$disk" \
+        # Create a 2MB BIOS Boot Partition first
+        sgdisk -n 1:0:+2M -t 1:ef02 -c 1:"BIOS boot partition" "$disk" \
+        || errorDisk "create_bios_boot"
+        # Create swap partition
+        sgdisk -n 2:0:+"$swap_size"G -t 2:8200 -c 2:"Linux swap" "$disk" \
         || errorDisk "create_swap"
     fi
 
-    sgdisk -n 2:0:0 -t 2:8300 -c 2:"Linux root" "$disk" \
+    if [[ $is_uefi -eq 0 ]]; then
+        sgdisk -n 2:0:0 -t 2:8300 -c 2:"Linux root" "$disk" \
         || errorDisk "create_root"
+    else
+        sgdisk -n 3:0:0 -t 3:8300 -c 3:"Linux root" "$disk" \
+        || errorDisk "create_root"
+    fi
 
     [[ -n $second_disk ]] && {
         sgdisk -n 1:0:0 -t 1:8300 -c 1:"Linux home" "$second_disk" \
@@ -158,10 +168,11 @@ setupPartitions() {
         mkdir -p /mnt/boot/efi || errorDisk "create_efi_mount"
         mount "${disk}1" /mnt/boot/efi || errorDisk "mount_efi"
     else
-        mkswap "${disk}1" || errorDisk "create_swap"
-        mkfs.ext4 "${disk}2" || errorDisk "format_root"
-        mount "${disk}2" /mnt || errorDisk "mount_root"
-        swapon "${disk}1" || errorDisk "enable_swap"
+        # Note: partition 1 is BIOS boot, no formatting needed
+        mkswap "${disk}2" || errorDisk "create_swap"
+        mkfs.ext4 "${disk}3" || errorDisk "format_root"
+        mount "${disk}3" /mnt || errorDisk "mount_root"
+        swapon "${disk}2" || errorDisk "enable_swap"
     fi
 
     [[ -n $second_disk ]] && {
