Updated a bunch of scripts

diff --git a/scripts/various/mediarenamer b/scripts/various/mediarenamer
--- a/scripts/various/mediarenamer
+++ b/scripts/various/mediarenamer
@@ -12,26 +12,20 @@ color_off=$'\e[0m';
 red=$'\e[0;31m';
 green=$'\e[0;32m';
 
-
 [[ -z $(command -v mediainfo) ]] && {
-    echo " ${red}Missing dependencies...mediainfo"
-    exit 1
+    echo " ${red}Missing dependency...mediainfo"
+    exit 127
 }
 
 _if_ext() {
-    if [[ "$media" =~ .mkv ]]; then
-        mv "$media" "$(cat newname.txt)".mkv
-    elif [[ "$media" =~ .mp3 ]]; then
-        mv "$media" "$(cat newname.txt)".mp3
-    elif [[ "$media" =~ .mp4 ]]; then
-        mv "$media" "$(cat newname.txt)".mp4
-    elif [[ "$media" =~ .flac ]]; then
-        mv "$media" "$(cat newname.txt)".flac
-    elif [[ "$media" =~ .ogg ]]; then
-        mv "$media" "$(cat newname.txt)".ogg
-    else
-        mv "$media" "$(cat newname.txt)".wav
-    fi
+    case "$media" in
+        .mkv ) mv "$media" "$(cat newname.txt)".mkv  ;;
+        .mp3 ) mv "$media" "$(cat newname.txt)".mp3  ;;
+        .mp4 ) mv "$media" "$(cat newname.txt)".mp4  ;;
+        .flac) mv "$media" "$(cat newname.txt)".flac ;;
+        .ogg ) mv "$media" "$(cat newname.txt)".ogg  ;;
+        *    ) mv "$media" "$(cat newname.txt)".wav  ;;
+    esac
 }
 
 # Replacing spaces with underscores.
@@ -52,10 +46,10 @@ select media in $(find . -name "*.mkv" -o -name "*.mp3" -o -name "*.mp4" \
     -o -name "*.flac" -o -name "*.ogg" -o -name "*.wav" | sed 's,.*/,,'); do
 
     if [[ $(mediainfo "$media" | grep -e 'Track name') ]]; then
-        echo " ${green}$media" metadatas:${color_off}
-        mediainfo "$media"
+        echo " ${green}${media} metadatas:${color_off}"
+        mediainfo "${media}"
         sleep 5
-        mediainfo "$media" \
+        mediainfo "${media}" \
         | grep -e 'Track name' \
         | sed -n '1p' \
         | sed 's/Track name//;s/^ *[[:space:]]//;s/: //' > newname.txt
@@ -67,16 +61,16 @@ select media in $(find . -name "*.mkv" -o -name "*.mp3" -o -name "*.mp4" \
         _if_ext
 
     else
-        echo " ${green}$media" metadatas:${color_off}
-        mediainfo "$media"
+        echo " ${green}${media} metadatas:${color_off}"
+        mediainfo "${media}"
         sleep 5
-        mediainfo "$media" \
+        mediainfo "${media}" \
         | grep -e 'Complete name' \
         | sed 's/Complete name//;s/^ *[[:space:]]//;s/: //' > newname.txt
         echo " ${green}The suggested file name is: ${red}"$(cat newname.txt)""
         echo " ${green}Copy/paste it, or pick another one.${color_off}"
         read -r newname
-        echo "$newname" > newname.txt
+        echo "${newname}" > newname.txt
 
         _if_ext
 
@@ -84,7 +78,7 @@ select media in $(find . -name "*.mkv" -o -name "*.mp3" -o -name "*.mp4" \
 
     rm newname.txt
 
-# Replacing underscores with spaces.
+    # Replacing underscores with spaces.
     if [[ -n $(find . -depth -name "*_*") ]]; then
         find . -depth -name "*_*" -exec \
         bash -c '
diff --git a/scripts/various/polybar_control b/scripts/various/polybar_control
--- a/scripts/various/polybar_control
+++ b/scripts/various/polybar_control
@@ -1,59 +1,99 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-# Manage polybar instances individually using -p option.
-# For instance: 3 monitors (3 bars), 3 window managers
-# bspwm-bar-{1,2,3} i3-bar-{1,2,3} & dk-bar-{1,2,3}
+# Author: Barret E <https://github.com/archusXIV/dofiles>
+# Manage polybar instances individually using -p option and fullscreen state.
+# For instance: 3 monitors (3 bars), 3 window managers (dk, bspwm, i3)
+# Dependencies: awk polybar wmctrl
 #
-# -r: Restarts the bar(s).
-# -t: Toggles between the hidden and visible state.
-# $MONITOR{1,2,3} are environment variables
-# shellcheck disable=SC2015
+# a = all                               | keyboard shortcuts (sxhkd)
+# -f: Toggles fullscreen mode           | ctrl + {_,alt,shift} + {1-4}
+# -r: Restarts the bar(s).              |     polybar_control -{t,f,r}{1,2,3,a}
+# -t: Toggles hidden and visible state. |
+#
+# ctrl + 1: toggles visibility of polybar on screen one
+# ctrl + a: toggles visibility of polybar on all screens
+# ctrl + alt + 1: toggles focused window fullscreen on screen one
+# ctrl + alt + a: toggles last focused windows fullscreen on all screens
+# ctrl + shift + 1: restarts polybar on screen one
+# ctrl + shift + a: restarts all polybar instances
+# See: man polybar-msg
 
-WM_NAME=$(wmctrl -m | awk '/Name:/{print $2}')
-barpid_1=$(pgrep --full "$WM_NAME"-bar-1)
-barpid_2=$(pgrep --full "$WM_NAME"-bar-2)
-barpid_3=$(pgrep --full "$WM_NAME"-bar-3)
+for dep in awk polybar wmctrl; do
+    command -v "${dep}" >/dev/null || {
+        echo "$dep is not installed. Exiting..."
+        exit 127
+    }
+done
 
-_Fullscreen() {
-    if [[ $WM_NAME == bspwm ]]; then
-        [[ $(bspc query -N -n focused.fullscreen) ]] \
-            && bspc node focused -t tiled \
-            || bspc node focused -t fullscreen
-    elif [[ $WM_NAME == i3 ]]; then
-        i3-msg fullscreen toggle
-    elif [[ $WM_NAME == dk ]]; then
-        dkcmd win full
-    fi
-}
+# Getting monitors names and polybar pids
+mapfile -t monitors < <(polybar -M | awk -F: '{print $1}')
+mapfile -t barpids < <(pgrep polybar)
+
+((${#barpids[@]} != ${#monitors[@]})) && exit 1
+
+for ((i=0;i<${#monitors[@]};i++)); do
+    monitor+=("$((i+1))")
+    barpid+=("${barpids[$i]}")
+done
+
+declare -A mon_id pid_id
+for ((i=1;i<=${#monitor[@]};i++)); do
+    mon_id[$i]="${monitor[$((i-1))]}"
+    pid_id[$i]="${barpid[$((i-1))]}"
+done
+
+action="${1#-}"
+option="${action:0:1}"
+num="${action:1}"
+wm_name=$(wmctrl -m | awk '/Name:/{print $2}')
 
 _WmFocusMonitor() {
-    if [[ $WM_NAME == bspwm ]]; then
-        bspc monitor -f "$1"
-    elif [[ $WM_NAME == i3 ]]; then
-        i3-msg focus output "$1"
-    elif [[ $WM_NAME == dk ]]; then
-        dkcmd mon "$1"
-    fi
+    [[ $wm_name == dk ]] && dkcmd mon "${mon_id[$num]}"
+    [[ $wm_name == bspwm ]] && bspc monitor -f "${mon_id[$num]}"
+    [[ $wm_name == i3 ]] && i3-msg focus output "${mon_id[$num]}"
 }
 
-case "$1" in
-    -t1)
-        _WmFocusMonitor "$MONITOR1" \
-         && polybar-msg -p "$barpid_1" cmd toggle \
-         && _Fullscreen
+_ToggleFullscreen() {
+    case "$1" in
+        --all)
+            # awk has to ignore polybar ids from wmctrl output
+            # if the window manager can or do manage them.
+            wmctrl -l | awk '$2 != -1 {print $1}' \
+            | xargs -I {} wmctrl -i -r {} -b toggle,fullscreen
+        ;;
+        --focused)
+            _WmFocusMonitor
+            [[ $wm_name == dk ]] && { dkcmd win full; exit; }
+            # No need to test $WM here, this test will fail if bspwm isn't running
+            [[ -n $(bspc query -N -n focused.fullscreen) ]] && {
+                bspc node focused -t tiled || bspc node focused -t fullscreen
+                exit
+            }
+            [[ $wm_name == i3 ]] && { i3-msg fullscreen toggle; exit; }
+        ;;
+    esac
+}
+
+[[ -z $num && -n "$2" ]] && num="$2"
+[[ $option == f && $num == a ]] && _ToggleFullscreen --all
+[[ $option == t && $num == a ]] && { polybar-msg cmd toggle; exit; }
+[[ $option == r && $num == a ]] && { polybar-msg cmd restart; exit; }
+
+case "$option" in
+    f) _ToggleFullscreen --focused ;;
+    r)
+        [[ -n "${pid_id[$num]}" ]] || { echo "Invalid bar number: $num"; exit 1; }
+        polybar-msg -p "${pid_id[$num]}" cmd restart
     ;;
-    -t2)
-        _WmFocusMonitor "$MONITOR2" \
-        && polybar-msg -p "$barpid_2" cmd toggle \
-        && _Fullscreen
+    t)
+        [[ -n "${mon_id[$num]}" ]] || { echo "Invalid monitor number: $num"; exit 1; }
+        _WmFocusMonitor "${mon_id[$num]}"
+        polybar-msg -p "${pid_id[$num]}" cmd toggle
     ;;
-    -t3)
-        _WmFocusMonitor "$MONITOR3" \
-        && polybar-msg -p "$barpid_3" cmd toggle \
-        && _Fullscreen
+    *)
+        echo "Invalid option: $option"
+        exit 1
     ;;
-    -r1) polybar-msg -p "$barpid_1" cmd restart ;;
-    -r2) polybar-msg -p "$barpid_2" cmd restart ;;
-    -r3) polybar-msg -p "$barpid_3" cmd restart ;;
-    -ra) "$SCRIPTDIR"/launch_polybar & exit ;;
 esac
+exit
+
diff --git a/scripts/various/screencaster b/scripts/various/screencaster
--- a/scripts/various/screencaster
+++ b/scripts/various/screencaster
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
-# Author: Barret E 2025 <archus@protonmail.com>
-# Script name: screencaster
+# Author: Barret E 2026 <archus@protonmail.com>
+# Script name: screencaster v1.2.1
 # License: GPlv2
 #
 # This script records the chosen screen with both video and audio
@@ -9,65 +9,88 @@
 # It requires command line arguments like:
 # screencaster -m HDMI-A-0 -a alsa_output.pci-0000_0a_00.4.analog-stereo.monitor
 # If -m or -a is not provided, we will be prompt to set those required parameters.
+# Use Ctrl+C to end the script if launched with -l or -w options
 # See the _Usage function for more options/info.
 # You can also check the filters parameters and change them in the FILTERS array.
 
-# shellcheck disable=SC2140
+# colors
+grn=$'\e[32m'
+red=$'\e[31m'
+noc=$'\e[0m'
 
 reset
-declare -a dependencies=(
-    ffmpeg
-    pulseaudio
-    awk
-    xrandr
-)
+declare -a dependencies=( awk ffmpeg pulseaudio xrandr wmctrl )
 
 for dependency in "${dependencies[@]}"; do
     command -v "${dependency}" >/dev/null || {
-        printf '%s\n' " $dependency isn't installed, exiting."
+        printf '%s\n' " ${red}$dependency isn't installed, exiting.${noc}"
         exit 127
     }
 done
 
-grn=$'\e[32m';
-red=$'\e[31m';
-nc=$'\e[0m';
 now=$(date +%Y-%m-%d_%H:%M:%S)
 
+mapfile -t active_monitors < <(
+    xrandr --listactivemonitors | awk 'NR>1 {print $NF}'
+)
+
+max_resolution=$(
+    xrandr | awk '/current/{print $8 "x" substr($10, 1, length($10)-1)}'
+)
+
+mapfile -t audio_sources < <(pactl list sources short | awk '{print $2}')
+
 _Usage() {
+    # setting a minimum window size to display this _Usage function correctly
+    wmctrl -r :ACTIVE: -e "5,-1,-1,1100,700"
+    echo
     printf '%s\n' \
-    " Usage: ${0##*/} [OPTION] [ARG]" \
-    " -a <audio source>  See down below available sources (required!)" \
-    " -b <yes/no>        Activate polybar mic/volume modules (default:no)" \
-    " -d <audio delay>   If needed, to sync audio/video in milliseconds (default:0)" \
-    " -D <add decibells> Number of decibells to add for the final result (default:1)" \
-    " -f <audio filter>  compressor, denoiser, cutfreq (one filter only)" \
-    " -l <length>        How long the screencast should last (format = HH:MM:SS)" \
-    " -m <monitor name>  example: HDMI-A-0 (required!)" \
-    " -o <filename>      Output file (default:$HOME/screencast_$now.mkv)" \
-    " -p <preset ratio>  Set the video quality (default:veryfast)" \
-    " -r <resolution>    Set the screen resolution (default:1920x1080)" \
-    " -v <volume>        Set the audio source level (in percentage) using pactl (default:80)"
-    echo -e "\n ${grn}Currently available audio sources:\n${nc}"
-    pactl list sources short | awk '{print "  "$2}'
+    " Usage: ${0##*/} [OPTIONS] [ARGS]" \
+    "" \
+    " -a <audio source>   :See down below available sources (required!)" \
+    " -b <yes/no>         :Activate polybar mic/volume modules (default:no)" \
+    " -d <audio delay>    :If needed, to sync audio/video in milliseconds (default:100)" \
+    " -D <add decibells>  :Number of decibells to add for the final result (default:1)" \
+    " -f <audio filter>   :compressor, denoiser, cutfreq (only one filter at a time)" \
+    " -F <framerate>      :change ffmpeg framerate parameter (default:30)" \
+    " -h|--help           :Print this message and exit" \
+    " -l <duration>       :How long the screencast should last (format = HH:MM:SS)" \
+    " -m <monitor name>   :Example: HDMI-A-0 (required!)" \
+    " -o <filename>       :Output file (default:$HOME/screencast_$now.mkv)" \
+    " -p <preset ratio>   :Set the video quality (default:veryfast)" \
+    " -r <resolution>     :Set the screen resolution (default:1920x1080)" \
+    " -t <duration>       :Set a timer before starting the recording (format = HH:MM:SS)" \
+    " -v <volume>         :Set the audio source level (in percentage) using pactl (default:90)" \
+    " -w <webcam/prog>    :Set a webcam program or script to display your own face" \
+    "" \
+    "  ${grn}Audio source(s) currently available:${noc}" \
+    "${audio_sources[@]}" \
+    "" \
+    "  ${grn}Maximum screen resolution: ${noc}$max_resolution" \
+    "  (if you want to use this and have multiple monitors, choose your first monitor)" \
+    "  ${grn}Example: ${red}screencaster -r $max_resolution -m ${active_monitors[0]}${noc}"
     exit 1
 }
 
-[[ $# -eq 0 ]] && _Usage
+[[ $# -eq 0 || $1 =~ -h|--help ]] && _Usage
+
 # Parsing arguments
-while getopts "a:b:d:D:f:l:m:o:p:r:v:" opt; do
+while getopts "a:b:d:D:f:F:l:m:o:p:r:t:v:w:" opt; do
     case $opt in
         a) audio_source="${OPTARG}" ;;
         b) bar="${OPTARG}" ;;
         d) audio_delay="${OPTARG}" ;;
         D) ndB="${OPTARG}" ;;
         f) filter="${OPTARG}" ;;
+        F) framerate="${OPTARG}" ;;
         l) length="${OPTARG}" ;;
         m) monitor="${OPTARG}" ;;
         o) output_file="${OPTARG}" ;;
         p) preset="${OPTARG}";;
         r) resolution="${OPTARG}" ;;
+        t) timer="${OPTARG}" ;;
         v) volume="${OPTARG}" ;;
+        w) webcam="${OPTARG}" ;;
         *) _Usage ;;
     esac
 done
@@ -83,19 +106,20 @@ declare -A FILTERS=(
 )
 
 # Default values
-audio_delay=${audio_delay:-0}
-bar=${bar:-no}
-ndB=${ndB:-1}
-output_file=${output_file:-"$HOME"/screencast_"$now".mkv}
-preset=${preset:-veryfast}
-resolution=${resolution:-"1920x1080"}
-volume=${volume:-80}
+: "${audio_delay:=100}"
+: "${bar:=no}"
+: "${framerate:=30}"
+: "${ndB:=1}"
+: "${output_file:=$HOME/screencast_$now.mkv}"
+: "${preset:=veryfast}"
+: "${resolution:=1920x1080}"
+: "${volume:=90}"
 
 # Validate filter if provided
 if [[ -n $filter ]]; then
     if [[ -z ${FILTERS[$filter]} ]]; then
-        echo " ${red}Invalid filter: $filter${nc}"
-        echo " Available filters: ${grn}${!FILTERS[*]}${nc}"
+        echo " ${red}Invalid filter: $filter"
+        echo " Available filters: ${grn}${!FILTERS[*]}${noc}"
         exit 1
     fi
     filter=${FILTERS[$filter]}
@@ -106,8 +130,8 @@ fi
 # Giving a menu for monitor choice if not provided
 [[ -z $monitor ]] && {
     printf '\n'
-    PS3=""$'\n'" ${grn}Select a monitor: ${nc}"
-    select m in $(xrandr --listactivemonitors | awk '$0 !~ /Monitor/{print $NF}'); do
+    PS3=""$'\n'" ${grn}Select a monitor: ${noc}"
+    select m in "${active_monitors[@]}"; do
         if [[ -n ${m+x} ]]; then
             monitor="$m"
             break
@@ -120,8 +144,8 @@ fi
 # ...and for audio source device too.
 [[ -z $audio_source ]] && {
     printf '\n'
-    PS3=""$'\n'" ${grn}Select an audio source: ${nc}"
-    select a in $(pactl list sources short | awk '{print "  "$2}'); do
+    PS3=""$'\n'" ${grn}Select an audio source: ${noc}"
+    select a in "${audio_sources[@]}"; do
         if [[ -n ${a+x} ]]; then
             audio_source="$a"
             [[ $audio_source =~ output && -z $volume ]] && volume=50
@@ -132,23 +156,31 @@ fi
     done
 }
 
+_IsPolybarActive() {
+    if [[ -n $(pgrep polybar) && $bar == "yes" ]]; then
+        return 0
+    else
+        return 1
+    fi
+}
+
 _BarActions() {
+    pid=$(pgrep -f "$(wmctrl -m | awk '/Name/{print $2}')"-bar-2)
     case "$1" in
         on)
             if [[ $input == "on" ]]; then
-                polybar-msg action "#mic-ipc.hook.1"
-                polybar-msg action "#volume-ipc.hook.0"
+                polybar-msg -p "$pid" action "#mic-ipc.hook.1"
+                polybar-msg -p "$pid" action "#volume-ipc.hook.0"
             elif [[ $output == "on" ]]; then
-                polybar-msg action "#mic-ipc.hook.0"
-                polybar-msg action "#volume-ipc.hook.1"
+                polybar-msg -p "$pid" action "#mic-ipc.hook.0"
+                polybar-msg -p "$pid" action "#volume-ipc.hook.1"
             fi
         ;;
         off)
-            polybar-msg action "#mic-ipc.hook.0"
-            polybar-msg action "#volume-ipc.hook.1"
+            polybar-msg -p "$pid" action "#mic-ipc.hook.0"
+            polybar-msg -p "$pid" action "#volume-ipc.hook.1"
         ;;
     esac
-
 } >/dev/null 2>&1
 
 _GetInputMute() { pactl get-source-mute @DEFAULT_SOURCE@; }
@@ -160,7 +192,7 @@ _SetOutputVolume() { pactl set-sink-volume @DEFAULT_SINK@ "$1"; }
 # Getting the current volume level so we can restore it when stopping the recording
 read -r currentvolume < <(
     pactl get-sink-volume @DEFAULT_SINK@ \
-    | awk '{if(NR!=2) {print $5}}'
+    | awk 'NR==1 {print $5}'
 )
 
 _SetVolume() {
@@ -174,7 +206,7 @@ _SetVolume() {
                 }
                 _SetInputVolume "$volume"%
                 input=on
-                [[ $bar == "yes" ]] && _BarActions on
+                _IsPolybarActive && _BarActions on
             elif [[ $audio_source =~ output ]]; then
                 _GetOutputMute | grep -q 'yes' && _SetOutputMute false
                 _GetInputMute | grep -q 'no' && {
@@ -183,7 +215,7 @@ _SetVolume() {
                 }
                 _SetOutputVolume "$volume"%
                 output=on
-                [[ $bar == "yes" ]] && _BarActions on
+                _IsPolybarActive && _BarActions on
             fi
             gsettings set org.gnome.desktop.sound event-sounds false
             ;;
@@ -193,20 +225,17 @@ _SetVolume() {
                 _SetInputMute true
                 _SetOutputMute false
                 _SetOutputVolume "${currentvolume}"
-                [[ $bar == "yes" ]] && _BarActions off
+                _IsPolybarActive && _BarActions off
             }
             [[ $output == "on" ]] && {
                 _SetOutputVolume "${currentvolume}"
                 _SetOutputMute false
-                [[ $bar == "yes" ]] && _BarActions off
+                _IsPolybarActive && _BarActions off
             }
             gsettings set org.gnome.desktop.sound event-sounds true
         ;;
     esac
 }
-
-[[ -n $volume ]] && _SetVolume on
-
 
 # Get monitor position (xrandr output)
 monitor_position=$(
@@ -218,34 +247,51 @@ monitor_position=$(
 )
 
 if [[ -z $monitor_position ]]; then
-    echo " ${red}Could not determine monitor position for $monitor${nc}"
+    echo " ${red}Could not determine monitor position for $monitor${noc}"
     exit 1
+else
+    x=${monitor_position%,*}
+    y=${monitor_position#*,}
 fi
-
-x=${monitor_position%,*}
-y=${monitor_position#*,}
 
 _EndScreencast() {
     [[ -n $volume ]] && _SetVolume off
+    kill -TERM "$(cat /tmp/webcampid)" 2>/dev/null
+    kill -TERM "$(pidof ffmpeg)"
     reset
     notify-send 'screencast is over'
     exit 0
 }
 
+[[ -n $volume ]] && _SetVolume on
+
+[[ -n $webcam ]] && {
+    "$webcam" &
+    webcam_pid=$!
+    echo "$webcam_pid" > /tmp/webcampid
+    trap 'kill -TERM "$(pidof ffmpeg)" "$webcam_pid"; _EndScreencast' SIGINT SIGTERM
+}
+
+# Translating user input into seconds
 _TimeConverter() {
     IFS=":";
-    if [[ $1  =~ ^[0-9]{2}:[0-9]{2}$ ]]; then
+    if [[ $1 =~ ^[0-9]{2}:[0-9]{2}$ ]]; then
         read -r minutes seconds <<< "$1"
         total_seconds=$((minutes * 60 + seconds))
-    elif [[ $1  =~ ^[0-9]{2}:[0-9]{2}:[0-9]{2}$ ]]; then
+    elif [[ $1 =~ ^[0-9]{2}:[0-9]{2}:[0-9]{2}$ ]]; then
         read -r hours minutes seconds <<< "$1"
         total_seconds=$(((hours * 3600) + (minutes * 60 + seconds)))
     else
         unset IFS
-        printf '\n%s\n' " ${red}Wrong duration format...${nc}"
+        printf '\n%s\n' " ${red}Wrong duration format...${noc}"
         _Usage
     fi
     unset IFS
+}
+
+[[ -n $timer ]] && {
+    _TimeConverter "$timer"
+    sleep "$total_seconds"
 }
 
 [[ -n $length ]] && {
@@ -254,15 +300,10 @@ _TimeConverter() {
     (
         for ((i=1;i<="$total_seconds";i++)); do
             sleep 1
-            (( i == total_seconds )) && {
-                kill -TERM "$(pidof ffmpeg)"
-                _EndScreencast
-            }
         done
+        _EndScreencast
     ) &
     timer_pid=$!
-
-    # Trap SIGINT/SIGTERM to kill both ffmpeg and the timer process
     trap 'kill -TERM "$(pidof ffmpeg)" "$timer_pid"; _EndScreencast' SIGINT SIGTERM
 }
 
@@ -270,7 +311,7 @@ ffmpeg \
     -y \
     -thread_queue_size 512 \
     -video_size "$resolution" \
-    -framerate 30 \
+    -framerate "$framerate" \
     -f x11grab -i :0.0+"$x","$y" \
     -thread_queue_size 512 \
     -f pulse -i "$audio_source" \
diff --git a/scripts/various/ssr_hidden b/scripts/various/ssr_hidden
--- a/scripts/various/ssr_hidden
+++ b/scripts/various/ssr_hidden
@@ -1,103 +1,188 @@
 #!/usr/bin/env bash
 
 # Author: Barret E 2025 <archus@protonmail.com>
-# Script name: ssr_hidden v1.0.1
+# Script name: ssr_hidden v2.1.2
 # License: GPLv2
 #
-# simple script to run simplescreenrecorder in hidden mode
-# for the entered time & @screen. (see _usage function)
-# input-profiles directory contains {all,center,left,right}.conf files.
+# Script to run simplescreenrecorder in hidden mode
+# for a determined duration & @screen. (see _Usage function)
+# input-profiles directory contains:
+# {all_{input,output},left_{input,output},center_{input,output},right_{input,output}}.conf files.
+# For example center_output.conf captures the sound from the speakers
+# and center_input.conf from the microphone.
 
+grn=$'\e[32m';
+nc=$'\e[0m';
 _Has() { command -v "$1" >/dev/null; }
 
-for dep in pulseaudio simplescreenrecorder; do
+for dep in polybar pulseaudio simplescreenrecorder; do
     _Has "${dep}" || {
-        printf '%s\n' " $dep isn't installed, exiting."
-        exit 127
+        if [[ $dep == polybar ]]; then
+            printf '%s\n' " ${grn}polybar is not installed but optional${nc}"
+            sleep 2
+        else
+            printf '%s\n' " $dep isn't installed, exiting."
+            exit 127
+        fi
     }
 done
 
+trap _Close SIGINT SIGTERM
+
 ssr_fifo="$XDG_RUNTIME_DIR/ssr.fifo"
-configs_path="$XDG_CONFIG_HOME/simplescreenrecorder/input-profiles"
+profiles_path="$XDG_CONFIG_HOME/simplescreenrecorder/input-profiles"
+
+if [[ -p "$ssr_fifo" ]]; then
+    rm "$ssr_fifo" || exit 1
+    mkfifo "$ssr_fifo"
+else
+    mkfifo "$ssr_fifo"
+fi
 
 _Usage() {
     printf '%s\n' \
     " Usage:   ${0##*/} -v <volume> -d <duration> -p <profile>" \
-    " -v Set the microphone volume (default:80)" \
-    " -d Set the video duration" \
-    " -p Set the SimpleScreenRecorder profile to use (omit .conf)" \
+    " -b <yes/no>       Activate polybar mic/volume modules (optional)" \
+    " -d <hh:mm:ss>     Set the video duration" \
+    " -l <all>          List all input profiles" \
+    " -p <profile name> Set the SimpleScreenRecorder profile to use (omit .conf)" \
+    " -v <volume>       Set the microphone volume (default:90)" \
     "                   duration = hh:mm:ss" \
     " Example: ${0##*/} -v 80 -d 00:15:30 -p profile_name" \
     " or:         ${0##*/} -v 80 -d 15:30 -p profile_name"
-    printf '\n%s\n' " Profile(s) should be in $configs_path"
+    printf '\n%s\n' " Profile(s) should be in $profiles_path" \
+    "  ${grn}Audio source(s) currently available:${nc}"
+    pactl list sources short | awk '{print "  "$2}'
     [[ -p "$ssr_fifo" ]] && rm "$ssr_fifo"
     exit 1
 }
 
+(($# == 0)) && _Usage
 # getting user input according to _Usage function.
-while getopts "d:p:v:" opt; do
+while getopts "b:d:l:p:v:" opt; do
     case "${opt}" in
+        b) bar="${OPTARG}" ;;
         d) duration="${OPTARG}" ;;
+        l)
+            if ! find "$profiles_path" -name "*.conf"; then
+                printf '\n%s\n' " No profile found in $profiles_path!"
+                exit 1
+            else
+                printf '\n%s\n' " Available profiles: "
+                find "$profiles_path" -name "*.conf" -printf '%f\n' \
+                | sort \
+                | sed 's/^/ /;s/.conf//'
+                exit 0
+            fi
+        ;;
         p)
             profile="${OPTARG}.conf"
-            if [[ -z $(find "$configs_path" -name "$profile") ]]; then
+            if ! find "$profiles_path" -name "$profile"; then
                 printf '\n%s\n' " profile $profile does not exist!"
                 _Usage
             fi
         ;;
         v) volume="${OPTARG}%" ;;
-        *) _Usage ;;
+        \?)
+            echo " Invalid option -${OPTARG}" >&2
+            exit 1
+        ;;
     esac
 done
 
-[[ -z $duration && -z $profile ]] && {
-    printf '\n%s\n' " Missing arguments..."
+shift $(( OPTIND - 1 ))
+
+[[ -z $duration ]] && {
+    printf '\n%s\n' " Missing duration..."
     _Usage
 }
 
-volume=${volume:-80}
+# default values
+: "${bar:=no}"
+: "${volume:="90%"}"
+
+[[ -z $profile ]] && {
+    printf '\n'
+    PS3=""$'\n'" ${grn}Select a source profile: ${nc}"
+    select p in $(find "$profiles_path" -type f -printf '%f\n' | sort -d); do
+        if [[ -n ${p+x} ]]; then
+            profile="$p"
+            [[ $profile =~ _output && -z $volume ]] && volume="70%"
+            break
+        else
+            _Usage
+        fi
+    done
+}
 
 _BarActions() {
+    pid=$(pgrep -f "$(wmctrl -m | awk '/Name/{print $2}')"-bar-2)
     case "$1" in
         on)
-            polybar-msg action "#mic-ipc.hook.1"
-            polybar-msg action "#volume-ipc.hook.0"
+            if [[ $input == "on" ]]; then
+                polybar-msg -p "$pid" action "#mic-ipc.hook.1"
+                polybar-msg -p "$pid" action "#volume-ipc.hook.0"
+            elif [[ $output == "on" ]]; then
+                polybar-msg -p "$pid" action "#mic-ipc.hook.0"
+                polybar-msg -p "$pid" action "#volume-ipc.hook.1"
+            fi
         ;;
         off)
-            polybar-msg action "#mic-ipc.hook.0"
-            polybar-msg action "#volume-ipc.hook.1"
+            polybar-msg -p "$pid" action "#mic-ipc.hook.0"
+            polybar-msg -p "$pid" action "#volume-ipc.hook.1"
         ;;
     esac
 
 } >/dev/null 2>&1
 
 _GetInputMute() { pactl get-source-mute @DEFAULT_SOURCE@; }
+_GetOutputMute() { pactl get-sink-mute @DEFAULT_SINK@; }
 _SetInputMute() { pactl set-source-mute @DEFAULT_SOURCE@ "$1"; }
 _SetOutputMute() { pactl set-sink-mute @DEFAULT_SINK@ "$1"; }
 _SetInputVolume() { pactl set-source-volume @DEFAULT_SOURCE@ "$1"; }
 _SetOutputVolume() { pactl set-sink-volume @DEFAULT_SINK@ "$1"; }
-# Getting the current volume level so we can restore it when stopping the recording
+# Getting the current volume level so we can restore it when the recording ends
 read -r currentvolume < <(
-        pactl get-sink-volume @DEFAULT_SINK@ \
-        | awk '{if(NR!=2) {print $5}}'
-    )
+    pactl get-sink-volume @DEFAULT_SINK@ \
+    | awk 'NR==1 {print $5}'
+)
 
 _SetVolume() {
     case "$1" in
         on)
-            _GetInputMute | grep -q 'yes' && _SetInputMute false
-            _SetInputVolume "$volume"
-            _SetOutputVolume 0%
-            _SetOutputMute true
+            if [[ $profile =~ input ]]; then
+                _GetInputMute | grep -q 'yes' && _SetInputMute false
+                _GetOutputMute | grep -q 'no' && {
+                    _SetOutputVolume 0%
+                    _SetOutputMute true
+                }
+                _SetInputVolume "$volume"
+                input=on
+                [[ $bar == "yes" ]] && _BarActions on
+            elif [[ $profile =~ output ]]; then
+                _GetOutputMute | grep -q 'yes' && _SetOutputMute false
+                _GetInputMute | grep -q 'no' && {
+                    _SetInputVolume 0%
+                    _SetInputMute true
+                }
+                _SetOutputVolume "$volume"
+                output=on
+                [[ $bar == "yes" ]] && _BarActions on
+            fi
             gsettings set org.gnome.desktop.sound event-sounds false
-            _Has polybar && _BarActions on
-        ;;
+            ;;
         off)
-            _SetInputVolume 0%
-            _SetInputMute true
-            _SetOutputMute false
-            _SetOutputVolume "${currentvolume}"
-            _Has polybar && _BarActions off
+            if [[ $input == "on" ]]; then
+                _SetInputVolume 0%
+                _SetInputMute true
+                _SetOutputMute false
+                _SetOutputVolume "${currentvolume}"
+                [[ $bar == "yes" ]] && _BarActions off
+            elif [[ $output == "on" ]]; then
+                _SetOutputVolume "${currentvolume}"
+                _SetOutputMute false
+                [[ $bar == "yes" ]] && _BarActions off
+            fi
             gsettings set org.gnome.desktop.sound event-sounds true
         ;;
     esac
@@ -105,13 +190,12 @@ _SetVolume() {
 
 _Close() {
     unset IFS
+    echo "record-save" >&4; sleep 0.5
+    echo "quit" >&4; exec 4>&-
     rm "$ssr_fifo"
     _SetVolume off
-    notify-send -u critical 'ssr_hidden is over'
     reset
 } >/dev/null 2>&1
-
-trap _Close SIGINT SIGTERM
 
 _TimeConversion() {
     IFS=":";
@@ -130,22 +214,13 @@ _TimeConversion() {
 
 _TimeConversion "$duration"
 
-if [[ -p "$ssr_fifo" ]]; then
-    rm "$ssr_fifo" || exit 1
-    mkfifo "$ssr_fifo"
-else
-    mkfifo "$ssr_fifo"
-fi
-
 [[ -n $volume ]] && _SetVolume on
 # ssr commands
 simplescreenrecorder \
     --start-hidden \
-    --settingsfile="$configs_path/$profile" < "$ssr_fifo" &
+    --settingsfile="$profiles_path/$profile" < "$ssr_fifo" &
 
 exec 4> "$ssr_fifo"; sleep 0.5
 echo "record-start" >&4; sleep "$totalSeconds"
-echo "record-save" >&4; sleep 1
-echo "quit" >&4; exec 4>&-
-
+sleep 1
 _Close; exit 0
diff --git a/scripts/various/updates-manager b/scripts/various/updates-manager
--- a/scripts/various/updates-manager
+++ b/scripts/various/updates-manager
@@ -5,8 +5,8 @@
 #
 # Yet Another Updates Manager Script for Arch Linux based systems.
 # We need sudo privileges without password prompt for this script to work
-: "${XDG_RUNTIME_DIR:-/run/user/1000}"
 
+: "${XDG_RUNTIME_DIR:-/run/user/1000}"
 arch_list="$XDG_RUNTIME_DIR/archlinux.list"
 aur_list="$XDG_RUNTIME_DIR/aur.list"
 arch_aur_list="$XDG_RUNTIME_DIR/combined.list"
@@ -19,54 +19,45 @@ nc=$'\e[0m'
 r=$'\e[0;31m'
 g=$'\e[0;32m'
 
-declare -a deps=( "checkupdates" "reflector" "yay" )
+declare -a deps=( "checkupdates" "reflector" "wmctrl" "yay" )
 
-_Error() {
-    printf '%s\n' " ${r}ERROR: $1${nc}" >&2
-    exit "${2:-1}"
-}
+declare -a reboot_criteria=(
+    "amd-ucode"
+    "grub"
+    "linux-cachyos"
+    "linux-zen"
+    "linux-znver4"
+    "mesa"
+    "systemd"
+    "xorg-server"
+)
 
 _Cleanup() {
     rm -f {"$arch_list","$aur_list","$arch_aur_list"} >/dev/null 2>&1
     exit "${1:-0}"
 }
 
-_CheckDependencies() {
-    for dep in "${deps[@]}"; do
-        command -v "$dep" >/dev/null 2>&1 || \
-        _Error "Missing dependency: ${dep}" 127
-    done
-}
-
-#[[ -z $country ]] && _Error "Could not determine country" 1
-
-_CheckForUpdates() {
-    checkupdates > "$arch_list"
-    yay -Qua > "$aur_list"
-    cat "$arch_list" "$aur_list" > "$arch_aur_list"
-
-    # Clean up the combined list
-    sed -i -e '/^::/d' -e '/^\s*$/d' -e 's/^\s\+//' "$arch_aur_list"
-    awk -i inplace '!seen[$0]++' "$arch_aur_list"
+_Error() {
+    printf '%s\n' " ${r}ERROR: $1${nc}" >&2
+    exit "${2:-1}"
 }
 
 _PolybarHook() {
-    if pgrep -x polybar >/dev/null; then
-        polybar-msg action "#updates-ipc.hook.0" >/dev/null 2>&1
-        notify-send "Available update(s): $(wc -l < "$arch_aur_list")"
+    if pgrep -x polybar &>/dev/null; then
+        pid=$(pgrep -f "$(wmctrl -m | awk '/Name/{print $2}')"-bar-2)
+        polybar-msg -p "$pid" action "#updates-ipc.hook.0" >/dev/null 2>&1
+        notify-send -p "Available update(s): $(wc -l < "$arch_aur_list")"
     else
         notify-send "Available update(s): $(wc -l < "$arch_aur_list")"
     fi
 }
 
-_CleanFiles() {
-    sed -i '1,$d' {"$arch_list","$aur_list","$arch_aur_list"}
-    _PolybarHook
-}
-
 _CheckUpdates() {
-    _CheckDependencies
 
+    for dep in "${deps[@]}"; do
+        command -v "$dep" >/dev/null 2>&1 || \
+        _Error "Missing dependency: ${dep}" 127
+    done
     # Set trap for cleanup
     trap '_Cleanup' EXIT SIGINT SIGTERM
 
@@ -89,11 +80,18 @@ _CheckUpdates() {
             --sort rate \
             --save "$mirr" >/dev/null 2>&1
 
-        _CheckForUpdates
-        _PolybarHook
+        timeout 5 checkupdates > "$arch_list"
+        timeout 5 yay -Qua > "$aur_list"
+        cat "$arch_list" "$aur_list" > "$arch_aur_list"
 
+        # remove weird characters,
+        sed -i -e '/^::/d' -e '/^\s*$/d' -e 's/^\s\+//' "$arch_aur_list"
+        # and duplicates from combined.list
+        awk -i inplace '!seen[$0]++' "$arch_aur_list"
+        _PolybarHook
         sleep 3592s
     done &
+
 }
 
 _YesNoPrompt() {
@@ -133,8 +131,6 @@ _Snapshot() {
     local OLDER_SNAPSHOT_INDEX OLDER_SNAPSHOT_NAME
     # will remove the first snapshot & create a new one.
     if command -v timeshift >/dev/null; then
-        # sudo mount /dev/sdb2 /mnt
-        # sleep 3
         # awk '/^0/{print $3}' will match the first snapshot over three.
         OLDER_SNAPSHOT_INDEX=$(sudo timeshift --list | awk '/^0/{print $1}')
         OLDER_SNAPSHOT_NAME=$(sudo timeshift --list | awk '/^0/{print $3}')
@@ -145,8 +141,6 @@ _Snapshot() {
         else
             sudo timeshift --create --skip-grub --comment "Before updates"
         fi
-        sleep 2
-        # sudo umount -R /mnt
     else
         notify-send -u critical " ${g}Timeshift is not installed...${nc}"
         sleep 2
@@ -173,33 +167,23 @@ _PowerOptions() {
     _AskforSnapshot && _Snapshot
     _Installation
     case "$1" in
-        -n)
+        --no-reboot)
             sed -i '1,$d' {"$arch_list","$aur_list","$arch_aur_list"}
             _PolybarHook
             exit 0
         ;;
-        -p) sudo poweroff ;;
-        -r) sudo reboot ;;
+        --poweroff) poweroff ;;
+        --reboot) reboot ;;
     esac
 }
 
 _CheckReboot() {
 
-    declare -a criteria=(
-        "amd-ucode"
-        "grub"
-        "linux-zen"
-        "linux-znver4"
-        "mesa"
-        "systemd"
-        "xorg-server"
-    )
-
-    for pkg in "${criteria[@]}"; do
-        if grep -qw "${pkg}" "$arch_list"; then
+    for pkg in "${reboot_criteria[@]}"; do
+        if grep -qw "${pkg}" "$arch_aur_list"; then
             local restart
-            echo -e " ${r}${pkg} requires REBOOT!${nc}\n"
             restart="yes"
+            echo -e " ${r}${pkg} requires REBOOT!${nc}\n"
             break
         fi
     done
@@ -210,23 +194,23 @@ _CheckReboot() {
         _YesNoPrompt -n " ${r}Poweroff ${nc}after updates?" || {
             _YesNoPrompt " ${r}Reboot ${nc}after updates?" || {
                 unset restart
-                _PowerOptions -n
+                _PowerOptions --no-reboot
             }
-            _PowerOptions -r
+            _PowerOptions --reboot
         }
-        _PowerOptions -p
+        _PowerOptions --poweroff
     else
         echo -e " ${g}NO REBOOT NEEDED!${nc}\n"
         # Here the default is 'No Reboot'.
         _YesNoPrompt -n " ${r}Poweroff ${nc}after updates?" || {
-            _PowerOptions -n
+            _PowerOptions --no-reboot
         }
-        _PowerOptions -p
+        _PowerOptions --poweroff
     fi
 
 }
 
-_List() {
+_ListUpdates() {
 
     mapfile -t total_updates < "$arch_aur_list"
 
@@ -257,19 +241,17 @@ _List() {
         fi
 
         # then Arch...
-        mapfile -t arch_list_packages < "$arch_list"
-        if (( ${#arch_list_packages[@]} > 0 )); then
-            _CheckReboot
-        fi
+        mapfile -t arch_packages < "$arch_list"
+        (( ${#arch_packages[@]} > 0 )) && _CheckReboot
 
     fi
 
 }
 
 case "$1" in
-    --chck) _CheckUpdates ;;
+    --chck) [[ -f $arch_aur_list ]] || _CheckUpdates ;;
     --hook) _PolybarHook ;;
-    --list) _List ;;
+    --list) _ListUpdates ;;
     --snap) _AskforSnapshot && _Snapshot ;;
     *     ) _Error "Wrong option: $1" 1 ;;
 esac
diff --git a/scripts/various/vim_script b/scripts/various/vim_script
--- a/scripts/various/vim_script
+++ b/scripts/various/vim_script
@@ -4,43 +4,64 @@
 
 cd "$SCRIPTDIR" || exit 1
 
-PS3="Enter a script number to Chmod, Edit, Remove, or Rename: "
+editor=${VISUAL:-vim}
+
+clear
+
+PS3=" Enter a script number to Chmod, Edit, Remove, or Rename: "
 
 [[ -n $(find . -maxdepth 1 -perm 644) ]] && {
-    printf '%s\n' "THESE FILES ARE NOT EXECUTABLE:"
+    perl -E 'say "-" x 46'
+    printf '%s\n' "THESE FILES ARE NOT EXECUTABLE: "
     find . -maxdepth 1 -perm 644 | sed 's/.\///'
+    perl -E 'say "-" x 46'
     echo ""
 }
 
 # set the scripts list.
-select file in $(find "$SCRIPTDIR" -maxdepth 1 -type f | sort -d | sed 's,.*/,,'); do
+select file in $(find . -maxdepth 1 -type f | sort | sed 's,.*/,,'); do
     echo ""
     read -rp '[C]hmod, [E]dit, [R]emove, [r]ename the chosen script or QUIT [q]: ' action
     case "$action" in
-        C|c)    chmod u+x "$file"
-                printf '%s\n' "$file is now executable."
-
+        C|c)
+            chmod u+x "$file"
+            printf '%s\n' "$file is now executable."
+            sleep 2
         ;;
-        E|e)    $VISUAL "$file"
+        E|e)
+            "$editor" "$file"
+            printf '%s\n' "$file saved"
+            sleep 2
         ;;
-        R  )    printf '%s\n' "remove $file? [y/N]:"
-                read -rsn 1 del
-                case "$del" in
-                    y|yes|Y) rm "$file" && printf '%s\n' "$file removed"
-                    ;;
-                    n|no|N) printf '%s\n' "Deletion aborted"
-                    ;;
-                    *) printf '%s\n' "Unknown option...deletion aborted" && exit 1
-                    ;;
-                esac
+        R  )
+            printf '%s\n' "remove $file? [y/N]:"
+            read -rsn 1 del
+            case "$del" in
+                y|yes|Y)
+                    rm "$file" && printf '%s\n' "$file removed"
+                    sleep 2
+                ;;
+                n|no|N)
+                    printf '%s\n' "Deletion aborted" && sleep 2
+                ;;
+                *)
+                    printf '%s\n' "Unknown option...deletion aborted" \
+                    && sleep 2 && exit 1
+                ;;
+            esac
         ;;
-        r  )    printf '%s\n' "rename $file:"
-                read -r name
-                mv "$file" "$name"
-                printf '%s\n' "$file renamed to: $name"
+        r  )
+            printf '%s\n' "rename $file:"
+            read -r name
+            mv "$file" "$name"
+            printf '%s\n' "$file renamed to: $name"
+            sleep 2
         ;;
-        q)  exit 0
+        q)
+            exit 0
         ;;
     esac
+
     break
+
 done
