updated some scripts

diff --git a/scripts/various/screencaster b/scripts/various/screencaster
--- a/scripts/various/screencaster
+++ b/scripts/various/screencaster
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
-# Author: Barret E 2026 <archus@protonmail.com>
-# Script name: screencaster v1.2.1
+# Author: Barret E 2026 <https://github.com/archusXIV>
+# Script name: screencaster v1.2.2
 # License: GPlv2
 #
 # This script records the chosen screen with both video and audio
@@ -9,17 +9,19 @@
 # It requires command line arguments like:
 # screencaster -m HDMI-A-0 -a alsa_output.pci-0000_0a_00.4.analog-stereo.monitor
 # If -m or -a is not provided, we will be prompt to set those required parameters.
+# Recording multiple monitors at once can be done by providing the -r option
+# followed by the string 'max', so you won't be prompted to choose a monitor.
 # Use Ctrl+C to end the script if launched with -l or -w options
-# See the _Usage function for more options/info.
-# You can also check the filters parameters and change them in the FILTERS array.
+# See the _Usage function for more options/infos.
+# You can also check the filters parameters and change them in the FILTERS array @line 110.
 
 # colors
-grn=$'\e[32m'
 red=$'\e[31m'
+grn=$'\e[32m'
 noc=$'\e[0m'
 
 reset
-declare -a dependencies=( awk ffmpeg pulseaudio xrandr wmctrl )
+declare -a dependencies=( awk ffmpeg pulseaudio xrandr )
 
 for dependency in "${dependencies[@]}"; do
     command -v "${dependency}" >/dev/null || {
@@ -38,11 +40,15 @@ max_resolution=$(
     xrandr | awk '/current/{print $8 "x" substr($10, 1, length($10)-1)}'
 )
 
-mapfile -t audio_sources < <(pactl list sources short | awk '{print $2}')
+mapfile -t audio_sources < <(pactl list sources short | awk '{print  $2}')
+
+# getting actual terminal size
+read -r rows cols < <(stty size)
 
 _Usage() {
     # setting a minimum window size to display this _Usage function correctly
-    wmctrl -r :ACTIVE: -e "5,-1,-1,1100,700"
+    # wmctrl -r :ACTIVE: -e "5,-1,-1,1100,700" >/dev/null 2>&1
+    echo -ne '\e[8;30;108t'
     echo
     printf '%s\n' \
     " Usage: ${0##*/} [OPTIONS] [ARGS]" \
@@ -67,12 +73,14 @@ _Usage() {
     "${audio_sources[@]}" \
     "" \
     "  ${grn}Maximum screen resolution: ${noc}$max_resolution" \
-    "  (if you want to use this and have multiple monitors, choose your first monitor)" \
-    "  ${grn}Example: ${red}screencaster -r $max_resolution -m ${active_monitors[0]}${noc}"
+    "  (if you have multiple monitors and want to use them all, do not use -m monitor)" \
+    "  ${grn}Example: ${grn}screencaster ${red}-r max ${grn}etc...${noc}"
     exit 1
 }
 
 [[ $# -eq 0 || $1 =~ -h|--help ]] && _Usage
+
+trap '_EndScreencast' SIGINT SIGTERM EXIT
 
 # Parsing arguments
 while getopts "a:b:d:D:f:F:l:m:o:p:r:t:v:w:" opt; do
@@ -127,6 +135,13 @@ else
     filter=""
 fi
 
+# if we want to capture all our monitors or if we have only one,
+# we just have to use -r max and it'll make no difference for ffmpeg.
+[[ $resolution =~ 'max' ]] && {
+    resolution="$max_resolution"
+    monitor="${active_monitors[0]}"
+}
+
 # Giving a menu for monitor choice if not provided
 [[ -z $monitor ]] && {
     printf '\n'
@@ -157,7 +172,7 @@ fi
 }
 
 _IsPolybarActive() {
-    if [[ -n $(pgrep polybar) && $bar == "yes" ]]; then
+    if pgrep polybar >/dev/null && [[ $bar == "yes" ]]; then
         return 0
     else
         return 1
@@ -166,7 +181,7 @@ _IsPolybarActive() {
 
 _BarActions() {
     pid=$(pgrep -f "$(wmctrl -m | awk '/Name/{print $2}')"-bar-2)
-    case "$1" in
+    case $1 in
         on)
             if [[ $input == "on" ]]; then
                 polybar-msg -p "$pid" action "#mic-ipc.hook.1"
@@ -196,9 +211,14 @@ read -r currentvolume < <(
 )
 
 _SetVolume() {
-    case "$1" in
+    case $1 in
         on)
             if [[ $audio_source =~ input ]]; then
+                # when recording sound from logitech C920,
+                # disabling focus_automatic_continuous
+                # will prevent clicky sounds.
+                command -v v4l2-ctl &> /dev/null && \
+                v4l2-ctl --set-ctrl focus_automatic_continuous=0
                 _GetInputMute | grep -q 'yes' && _SetInputMute false
                 _GetOutputMute | grep -q 'no' && {
                     _SetOutputVolume 0%
@@ -247,55 +267,68 @@ monitor_position=$(
 )
 
 if [[ -z $monitor_position ]]; then
-    echo " ${red}Could not determine monitor position for $monitor${noc}"
+    printf '\n%s\n' " ${red}Could not determine monitor position for $monitor${noc}"
     exit 1
 else
     x=${monitor_position%,*}
     y=${monitor_position#*,}
 fi
 
-_EndScreencast() {
-    [[ -n $volume ]] && _SetVolume off
-    kill -TERM "$(cat /tmp/webcampid)" 2>/dev/null
-    kill -TERM "$(pidof ffmpeg)"
-    reset
-    notify-send 'screencast is over'
-    exit 0
-}
-
-[[ -n $volume ]] && _SetVolume on
-
-[[ -n $webcam ]] && {
-    "$webcam" &
-    webcam_pid=$!
-    echo "$webcam_pid" > /tmp/webcampid
-    trap 'kill -TERM "$(pidof ffmpeg)" "$webcam_pid"; _EndScreencast' SIGINT SIGTERM
-}
+_SetVolume on
 
 # Translating user input into seconds
 _TimeConverter() {
     IFS=":";
     if [[ $1 =~ ^[0-9]{2}:[0-9]{2}$ ]]; then
         read -r minutes seconds <<< "$1"
-        total_seconds=$((minutes * 60 + seconds))
+        # we should consider bash managing octals.
+        total_seconds=$(((10#$minutes * 60) + 10#$seconds))
     elif [[ $1 =~ ^[0-9]{2}:[0-9]{2}:[0-9]{2}$ ]]; then
         read -r hours minutes seconds <<< "$1"
-        total_seconds=$(((hours * 3600) + (minutes * 60 + seconds)))
+        total_seconds=$(((10#$hours * 3600) + (10#$minutes * 60 + 10#$seconds)))
     else
         unset IFS
         printf '\n%s\n' " ${red}Wrong duration format...${noc}"
+        sleep 2
         _Usage
     fi
     unset IFS
 }
 
+[[ -n $webcam ]] && {
+    "$webcam" &
+    echo $! > /tmp/screencast_pids
+}
+
 [[ -n $timer ]] && {
     _TimeConverter "$timer"
-    sleep "$total_seconds"
+    for ((i="$total_seconds";i>0;i--)); do
+        clear
+        printf '%s\n' " ${grn}screencast will start in: ${i} seconds" \
+            " on monitor: $monitor${noc}"
+        sleep 1
+    done
+    unset total_seconds
+}
+
+_EndScreencast() {
+    # restoring the previous terminal size
+    echo -ne "\e[8;${rows};${cols}t"
+    _SetVolume off
+    {
+        kill -TERM "$(pidof ffmpeg)"
+        while read -r line; do kill -TERM "$line"; done < /tmp/screencast_pids
+        rm /tmp/screencast_pids
+    } 2> /dev/null
+    reset
+    notify-send 'screencast is over'
+    exit
 }
 
 [[ -n $length ]] && {
-    _TimeConverter "$length" && sleep 0.2
+    _TimeConverter "$length"
+    printf '%s\n' " ${grn}Screencast will last for: $total_seconds seconds${noc}"
+    sleep 2
     # Start a background timer process and save its PID
     (
         for ((i=1;i<="$total_seconds";i++)); do
@@ -303,9 +336,11 @@ _TimeConverter() {
         done
         _EndScreencast
     ) &
-    timer_pid=$!
-    trap 'kill -TERM "$(pidof ffmpeg)" "$timer_pid"; _EndScreencast' SIGINT SIGTERM
+    echo $! >> /tmp/screencast_pids
 }
+
+# wmctrl -r :ACTIVE: -e "5,-1,-1,1350,130" >/dev/null 2>&1
+echo -ne '\e[8;5;133t'
 
 ffmpeg \
     -y \
@@ -315,8 +350,7 @@ ffmpeg \
     -f x11grab -i :0.0+"$x","$y" \
     -thread_queue_size 512 \
     -f pulse -i "$audio_source" \
-    -af "${audio_delay:+adelay=${audio_delay}|${audio_delay}}${audio_delay:+,}\
-        volume=${ndB}dB${filter:+,}${filter}" \
+    -af "${audio_delay:+adelay=${audio_delay}|${audio_delay}}${audio_delay:+,}volume=${ndB}dB${filter:+,}${filter}" \
     -c:v libx264 \
     -preset "$preset" \
     -crf 23 \
@@ -326,4 +360,4 @@ ffmpeg \
     -fps_mode cfr \
     "$output_file"
 
-_EndScreencast
+[[ -z $length ]] && _EndScreencast
diff --git a/scripts/various/ssr_hidden b/scripts/various/ssr_hidden
--- a/scripts/various/ssr_hidden
+++ b/scripts/various/ssr_hidden
@@ -1,29 +1,24 @@
 #!/usr/bin/env bash
 
-# Author: Barret E 2025 <archus@protonmail.com>
-# Script name: ssr_hidden v2.1.2
+# Author: Barret E 2025 <https://github.com/archusXIV>
+# Script name: ssr_hidden v2.1.4
 # License: GPLv2
 #
 # Script to run simplescreenrecorder in hidden mode
 # for a determined duration & @screen. (see _Usage function)
-# input-profiles directory contains:
+# My input-profiles directory contains:
 # {all_{input,output},left_{input,output},center_{input,output},right_{input,output}}.conf files.
 # For example center_output.conf captures the sound from the speakers
 # and center_input.conf from the microphone.
 
+red=$'\e[31m';
 grn=$'\e[32m';
-nc=$'\e[0m';
-_Has() { command -v "$1" >/dev/null; }
+noc=$'\e[0m';
 
-for dep in polybar pulseaudio simplescreenrecorder; do
-    _Has "${dep}" || {
-        if [[ $dep == polybar ]]; then
-            printf '%s\n' " ${grn}polybar is not installed but optional${nc}"
-            sleep 2
-        else
-            printf '%s\n' " $dep isn't installed, exiting."
-            exit 127
-        fi
+for dep in pulseaudio simplescreenrecorder; do
+    command -v "${dep}" >/dev/null || {
+        printf '%s\n' " ${red}$dep isn't installed, exiting.${noc}"
+        exit 127
     }
 done
 
@@ -32,40 +27,38 @@ trap _Close SIGINT SIGTERM
 ssr_fifo="$XDG_RUNTIME_DIR/ssr.fifo"
 profiles_path="$XDG_CONFIG_HOME/simplescreenrecorder/input-profiles"
 
-if [[ -p "$ssr_fifo" ]]; then
-    rm "$ssr_fifo" || exit 1
-    mkfifo "$ssr_fifo"
-else
-    mkfifo "$ssr_fifo"
-fi
-
 _Usage() {
     printf '%s\n' \
     " Usage:   ${0##*/} -v <volume> -d <duration> -p <profile>" \
-    " -b <yes/no>       Activate polybar mic/volume modules (optional)" \
-    " -d <hh:mm:ss>     Set the video duration" \
-    " -l <all>          List all input profiles" \
-    " -p <profile name> Set the SimpleScreenRecorder profile to use (omit .conf)" \
-    " -v <volume>       Set the microphone volume (default:90)" \
-    "                   duration = hh:mm:ss" \
+    " -b <yes/no>       :Activate polybar mic/volume modules (optional)" \
+    " -d <hh:mm:ss>     :Set the video duration" \
+    " -l <all>          :List all available input profiles" \
+    " -p <profile name> :Set the SimpleScreenRecorder profile to use (omit .conf)" \
+    " -t <hh:mm:ss>     :Set a timer before starting the recording" \
+    " -v <volume>       :Set the volume for input/output (default:90)" \
+    "" \
     " Example: ${0##*/} -v 80 -d 00:15:30 -p profile_name" \
-    " or:         ${0##*/} -v 80 -d 15:30 -p profile_name"
+    " or:      ${0##*/} -v 80 -d 15:30 -p profile_name"
     printf '\n%s\n' " Profile(s) should be in $profiles_path" \
-    "  ${grn}Audio source(s) currently available:${nc}"
+    "  ${grn}Audio source(s) currently available:${noc}"
     pactl list sources short | awk '{print "  "$2}'
     [[ -p "$ssr_fifo" ]] && rm "$ssr_fifo"
     exit 1
 }
 
-(($# == 0)) && _Usage
+[[ $# -eq 0 || $1 =~ -h|--help ]] && _Usage
+
+[[ -p $ssr_fifo ]] && rm "$ssr_fifo"
+mkfifo "$ssr_fifo"
+
 # getting user input according to _Usage function.
-while getopts "b:d:l:p:v:" opt; do
+while getopts "b:d:l:p:t:v:" opt; do
     case "${opt}" in
         b) bar="${OPTARG}" ;;
         d) duration="${OPTARG}" ;;
         l)
-            if ! find "$profiles_path" -name "*.conf"; then
-                printf '\n%s\n' " No profile found in $profiles_path!"
+            if ! find "$profiles_path" -name "*.conf" >/dev/null; then
+                printf '\n%s\n' " ${red}No profile found in $profiles_path!${noc}"
                 exit 1
             else
                 printf '\n%s\n' " Available profiles: "
@@ -77,14 +70,15 @@ while getopts "b:d:l:p:v:" opt; do
         ;;
         p)
             profile="${OPTARG}.conf"
-            if ! find "$profiles_path" -name "$profile"; then
-                printf '\n%s\n' " profile $profile does not exist!"
+            if ! find "$profiles_path" -name "$profile" >/dev/null; then
+                printf '\n%s\n' " ${red}profile $profile does not exist!${noc}"
                 _Usage
             fi
         ;;
+        t) timer="${OPTARG}" ;;
         v) volume="${OPTARG}%" ;;
         \?)
-            echo " Invalid option -${OPTARG}" >&2
+            echo " ${red}Invalid option -${OPTARG}${noc}" >&2
             exit 1
         ;;
     esac
@@ -93,7 +87,7 @@ done
 shift $(( OPTIND - 1 ))
 
 [[ -z $duration ]] && {
-    printf '\n%s\n' " Missing duration..."
+    printf '\n%s\n' " ${red}Missing duration...${noc}"
     _Usage
 }
 
@@ -103,7 +97,7 @@ shift $(( OPTIND - 1 ))
 
 [[ -z $profile ]] && {
     printf '\n'
-    PS3=""$'\n'" ${grn}Select a source profile: ${nc}"
+    PS3=""$'\n'" ${grn}Select a source profile: ${noc}"
     select p in $(find "$profiles_path" -type f -printf '%f\n' | sort -d); do
         if [[ -n ${p+x} ]]; then
             profile="$p"
@@ -113,6 +107,14 @@ shift $(( OPTIND - 1 ))
             _Usage
         fi
     done
+}
+
+_IsPolybarActive() {
+    if [[ -n $(pgrep polybar) && $bar == "yes" ]]; then
+        return 0
+    else
+        return 1
+    fi
 }
 
 _BarActions() {
@@ -151,6 +153,11 @@ _SetVolume() {
     case "$1" in
         on)
             if [[ $profile =~ input ]]; then
+                # when recording sound from logitech C920,
+                # disabling focus_automatic_continuous
+                # will prevent clicky sounds to occur.
+                command -v v4l2-ctl &> /dev/null && \
+                v4l2-ctl --set-ctrl focus_automatic_continuous=0
                 _GetInputMute | grep -q 'yes' && _SetInputMute false
                 _GetOutputMute | grep -q 'no' && {
                     _SetOutputVolume 0%
@@ -158,7 +165,7 @@ _SetVolume() {
                 }
                 _SetInputVolume "$volume"
                 input=on
-                [[ $bar == "yes" ]] && _BarActions on
+                _IsPolybarActive && _BarActions on
             elif [[ $profile =~ output ]]; then
                 _GetOutputMute | grep -q 'yes' && _SetOutputMute false
                 _GetInputMute | grep -q 'no' && {
@@ -167,21 +174,21 @@ _SetVolume() {
                 }
                 _SetOutputVolume "$volume"
                 output=on
-                [[ $bar == "yes" ]] && _BarActions on
+                _IsPolybarActive && _BarActions on
             fi
             gsettings set org.gnome.desktop.sound event-sounds false
-            ;;
+        ;;
         off)
             if [[ $input == "on" ]]; then
                 _SetInputVolume 0%
                 _SetInputMute true
                 _SetOutputMute false
                 _SetOutputVolume "${currentvolume}"
-                [[ $bar == "yes" ]] && _BarActions off
+                _IsPolybarActive && _BarActions off
             elif [[ $output == "on" ]]; then
                 _SetOutputVolume "${currentvolume}"
                 _SetOutputMute false
-                [[ $bar == "yes" ]] && _BarActions off
+                _IsPolybarActive && _BarActions off
             fi
             gsettings set org.gnome.desktop.sound event-sounds true
         ;;
@@ -189,38 +196,52 @@ _SetVolume() {
 }
 
 _Close() {
-    unset IFS
-    echo "record-save" >&4; sleep 0.5
-    echo "quit" >&4; exec 4>&-
     rm "$ssr_fifo"
     _SetVolume off
     reset
-} >/dev/null 2>&1
+    exit 0
+}
 
-_TimeConversion() {
+_TimeConverter() {
     IFS=":";
     if [[ $1  =~ ^[0-9]{2}:[0-9]{2}$ ]]; then
         read -r minutes seconds <<< "$1"
-        totalSeconds=$((minutes * 60 + seconds))
+        total_seconds=$(((10#$minutes * 60) + 10#$seconds))
     elif [[ $1  =~ ^[0-9]{2}:[0-9]{2}:[0-9]{2}$ ]]; then
         read -r hours minutes seconds <<< "$1"
-        totalSeconds=$(((hours * 3600) + (minutes * 60 + seconds)))
+        total_seconds=$(((10#$hours * 3600) + (10#$minutes * 60 + 10#$seconds)))
     else
-        printf '\n%s\n' " Wrong duration syntax..."
-        _Close; _Usage
+        unset IFS
+        printf '\n%s\n' " ${red}Wrong duration syntax...${noc}"
+        _Usage
     fi
     unset IFS
 }
 
-_TimeConversion "$duration"
+_Sleep() { read -r -t "$@"; }
+
+[[ -n $timer ]] && {
+    _TimeConverter "$timer"
+    # Giving a negative number to the seq command because
+    # seq only increments but we want to decrement $total_seconds until 0
+    for second in $(seq -"$total_seconds" 0); do
+        clear
+        echo " ${grn}recording will start in: ${second/-/} seconds${noc}"
+        _Sleep 1
+    done
+}
+
+_TimeConverter "$duration"
 
 [[ -n $volume ]] && _SetVolume on
-# ssr commands
+
+# the output filename and other settings are written in the selected profile
 simplescreenrecorder \
     --start-hidden \
     --settingsfile="$profiles_path/$profile" < "$ssr_fifo" &
 
-exec 4> "$ssr_fifo"; sleep 0.5
-echo "record-start" >&4; sleep "$totalSeconds"
-sleep 1
-_Close; exit 0
+exec 4> "$ssr_fifo"; _Sleep 0.5
+echo "record-start" >&4; _Sleep "$total_seconds"
+echo "record-save" >&4; _Sleep 0.5
+echo "quit" >&4; exec 4>&-
+_Close
diff --git a/scripts/various/updates-manager b/scripts/various/updates-manager
--- a/scripts/various/updates-manager
+++ b/scripts/various/updates-manager
@@ -1,50 +1,50 @@
 #!/usr/bin/env bash
 
-# Author: Barret E (2020-25) <archus@protonmail.con>
-# https://github.com/archusXIV/dotfiles
+# Author: Barret E (2020-26) <https://github.com/archusXIV/dotfiles>
 #
 # Yet Another Updates Manager Script for Arch Linux based systems.
-# We need sudo privileges without password prompt for this script to work
+# We need sudo privileges without password prompt for this script to work.
+# This script is also designed to work alongside polybar as it updates
+# my checkupdates module before and after processing system upgrade.
 
 : "${XDG_RUNTIME_DIR:-/run/user/1000}"
 arch_list="$XDG_RUNTIME_DIR/archlinux.list"
 aur_list="$XDG_RUNTIME_DIR/aur.list"
 arch_aur_list="$XDG_RUNTIME_DIR/combined.list"
-mirr="/etc/pacman.d/mirrorlist"
-bckp="$mirr"_bckp
-country=$(curl --fail -s https://ipapi.co/country)
+mirr_dir="/etc/pacman.d"
+arch_mirr="$mirr_dir/archlinux-mirrorlist"
+arch_bckp="$arch_mirr"_bckp
+cachyos_mirr="$mirr_dir/cachyos-mirrorlist"
+chaotic_mirr="$mirr_dir/chaotic-mirrorlist"
 
 # Colors
-nc=$'\e[0m'
-r=$'\e[0;31m'
-g=$'\e[0;32m'
+N=$'\e[0m'
+R=$'\e[0;31m'
+G=$'\e[0;32m'
 
-declare -a deps=( "checkupdates" "reflector" "wmctrl" "yay" )
-
-declare -a reboot_criteria=(
-    "amd-ucode"
-    "grub"
-    "linux-cachyos"
-    "linux-zen"
-    "linux-znver4"
-    "mesa"
-    "systemd"
-    "xorg-server"
+declare -a deps=(
+    "checkupdates"
+    "pacman"
+    "rankmirrors"
+    "reflector"
+    "wmctrl"
+    "yay"
 )
 
 _Cleanup() {
+    # This will stop the while loop in the _CheckUpdates function.
     rm -f {"$arch_list","$aur_list","$arch_aur_list"} >/dev/null 2>&1
     exit "${1:-0}"
 }
 
 _Error() {
-    printf '%s\n' " ${r}ERROR: $1${nc}" >&2
+    printf '%s\n' " ${R}ERROR: $1${N}" >&2
     exit "${2:-1}"
 }
 
 _PolybarHook() {
     if pgrep -x polybar &>/dev/null; then
-        pid=$(pgrep -f "$(wmctrl -m | awk '/Name/{print $2}')"-bar-2)
+        pid=$(pgrep --full "$(wmctrl -m | awk '/Name/{print $2}')"-bar-2)
         polybar-msg -p "$pid" action "#updates-ipc.hook.0" >/dev/null 2>&1
         notify-send -p "Available update(s): $(wc -l < "$arch_aur_list")"
     else
@@ -52,39 +52,71 @@ _PolybarHook() {
     fi
 }
 
+_rateMirrors() {
+
+    local repo="$1"
+    case $repo in
+        official)
+            sudo reflector \
+                --country "$(curl -s https://ipinfo.io/country)" \
+                --latest 10 \
+                --age 24 \
+                --protocol https \
+                --sort rate \
+                --save "$arch_mirr" >/dev/null 2>&1
+        ;;
+        third-party)
+            ! command -v rate-mirrors &>/dev/null && return 1
+            __rateThirdPartyMirrors() {
+                rate-mirrors \
+                --disable-comments \
+                --entry-country="$(curl -s https://ipinfo.io/country)" \
+                --exclude-countries=US,CA,CN,NZ,RU "$1"
+            }
+            [[ -f $cachyos_mirr ]] && {
+                __rateThirdPartyMirrors cachyos | sudo tee "$cachyos_mirr"
+                # shellcheck disable=SC2016
+                sed 's/\$arch/\$arch_v4/g' "$cachyos_mirr" \
+                | sudo tee /etc/pacman.d/cachyos-v4-mirrorlist
+            }
+            [[ -f $chaotic_mirr ]] && {
+                __rateThirdPartyMirrors chaotic-aur | sudo tee "$chaotic_mirr"
+            }
+        ;;
+        *)
+            printf '%s\n' " ${R}$repo does not exist${N}"
+            sleep 2
+            return 1
+        ;;
+    esac
+
+}
+
 _CheckUpdates() {
 
     for dep in "${deps[@]}"; do
         command -v "$dep" >/dev/null 2>&1 || \
-        _Error "Missing dependency: ${dep}" 127
+        _Error " ${R}Missing dependency: ${dep}${N}" 127
     done
     # Set trap for cleanup
-    trap '_Cleanup' EXIT SIGINT SIGTERM
+    trap '_Cleanup' SIGTERM
 
-    [[ -f $arch_list ]] && rm {"$arch_list","$aur_list","$arch_aur_list"} 2>/dev/null
-
-    while true; do
-        # Check network
+    while [[ -f $arch_aur_list ]]; do
+        # Checking the network
         if [[ -z $(ping -c 1 archlinux.org 2>/dev/null) ]]; then
             notify-send -u critical 'archlinux.org unreachable'
             _Cleanup 1
         fi
 
-        sudo cp -f "$mirr" "$bckp"
+        sudo cp -f "$arch_mirr" "$arch_bckp"
 
-        sudo reflector \
-            --country "$country" \
-            --latest 10 \
-            --age 24 \
-            --protocol https \
-            --sort rate \
-            --save "$mirr" >/dev/null 2>&1
+        _rateMirrors official
 
         timeout 5 checkupdates > "$arch_list"
         timeout 5 yay -Qua > "$aur_list"
         cat "$arch_list" "$aur_list" > "$arch_aur_list"
 
-        # remove weird characters,
+        # remove some weird characters possibly written by yay,
         sed -i -e '/^::/d' -e '/^\s*$/d' -e 's/^\s\+//' "$arch_aur_list"
         # and duplicates from combined.list
         awk -i inplace '!seen[$0]++' "$arch_aur_list"
@@ -128,45 +160,54 @@ _YesNoPrompt() {
 
 _Snapshot() {
 
-    local OLDER_SNAPSHOT_INDEX OLDER_SNAPSHOT_NAME
+    local older_snapshot_index older_snapshot_name
     # will remove the first snapshot & create a new one.
     if command -v timeshift >/dev/null; then
         # awk '/^0/{print $3}' will match the first snapshot over three.
-        OLDER_SNAPSHOT_INDEX=$(sudo timeshift --list | awk '/^0/{print $1}')
-        OLDER_SNAPSHOT_NAME=$(sudo timeshift --list | awk '/^0/{print $3}')
+        older_snapshot_index=$(sudo timeshift --list | awk '/^0/{print $1}')
+        older_snapshot_name=$(sudo timeshift --list | awk '/^0/{print $3}')
         # checking '0' as a string
-        if [[ $OLDER_SNAPSHOT_INDEX == '0' ]]; then
-            sudo timeshift --delete --snapshot "$OLDER_SNAPSHOT_NAME"
+        if [[ $older_snapshot_index == '0' ]]; then
+            sudo timeshift --delete --snapshot "$older_snapshot_name"
             sudo timeshift --create --skip-grub --comment "Before updates"
         else
             sudo timeshift --create --skip-grub --comment "Before updates"
         fi
     else
-        notify-send -u critical " ${g}Timeshift is not installed...${nc}"
+        notify-send -u critical " ${G}Timeshift is not installed...${N}"
         sleep 2
     fi
 
 }
 
 _AskforSnapshot() {
-    _YesNoPrompt " ${r}Do you want to create a snapshot?: ${nc}" || {
+    _YesNoPrompt " ${R}Do you want to create a snapshot?: ${N}" || {
         return 1
     }
     return 0
 }
 
 _Installation() {
-    sudo cp -f "$mirr" "$bckp"
-    echo "${g}Ranking mirrolist...be patient${nc}"
-    rankmirrors -n 10 "$bckp" | sudo tee "$mirr"
-    sudo pacman -Syu --noconfirm --disable-download-timeout
+    sudo cp -f "$arch_mirr" "$arch_bckp"
+    echo "${G}Ranking mirrolist...be patient${N}"
+    rankmirrors -n 10 "$arch_bckp" | sudo tee "$arch_mirr"
+    declare -a repos=(archlinux cachyos chaotic)
+    sudo pacman-key --init
+    for repo in "${repos[@]}"; do
+        sudo pacman-key --populate "$repo" && keyrings+=("$repo"-keyring)
+    done
+    sudo pacman \
+        -Syu \
+        --noconfirm \
+        --disable-download-timeout \
+        "${keyrings[@]}"
     sudo grub-mkconfig -o /boot/grub/grub.cfg
 }
 
 _PowerOptions() {
     _AskforSnapshot && _Snapshot
     _Installation
-    case "$1" in
+    case $1 in
         --no-reboot)
             sed -i '1,$d' {"$arch_list","$aur_list","$arch_aur_list"}
             _PolybarHook
@@ -177,22 +218,33 @@ _PowerOptions() {
     esac
 }
 
+declare -a reboot_criteria=(
+    "amd-ucode"
+    "grub"
+    "linux-cachyos"
+    "linux-firmware"
+    "linux-zen"
+    "linux-znver4"
+    "mesa"
+    "systemd"
+    "xorg-server"
+)
+
 _CheckReboot() {
 
+    local restart=0
     for pkg in "${reboot_criteria[@]}"; do
         if grep -qw "${pkg}" "$arch_aur_list"; then
-            local restart
-            restart="yes"
-            echo -e " ${r}${pkg} requires REBOOT!${nc}\n"
-            break
+            ((restart++))
         fi
     done
 
     # the default is reboot.
     # by pressing Enter we will get the default action.
-    if [[ -n $restart ]]; then
-        _YesNoPrompt -n " ${r}Poweroff ${nc}after updates?" || {
-            _YesNoPrompt " ${r}Reboot ${nc}after updates?" || {
+    if (( restart > 0 )); then
+        echo -e " ${R}Some critical packages require REBOOT!${N}\n"
+        _YesNoPrompt -n " ${R}Poweroff ${N}after updates?" || {
+            _YesNoPrompt " ${R}Reboot ${N}after updates?" || {
                 unset restart
                 _PowerOptions --no-reboot
             }
@@ -200,9 +252,9 @@ _CheckReboot() {
         }
         _PowerOptions --poweroff
     else
-        echo -e " ${g}NO REBOOT NEEDED!${nc}\n"
+        echo -e " ${G}NO REBOOT NEEDED!${N}\n"
         # Here the default is 'No Reboot'.
-        _YesNoPrompt -n " ${r}Poweroff ${nc}after updates?" || {
+        _YesNoPrompt -n " ${R}Poweroff ${N}after updates?" || {
             _PowerOptions --no-reboot
         }
         _PowerOptions --poweroff
@@ -212,28 +264,44 @@ _CheckReboot() {
 
 _ListUpdates() {
 
+    mapfile -t aur_updates < "$aur_list"
+    mapfile -t arch_updates < "$arch_list"
     mapfile -t total_updates < "$arch_aur_list"
 
     if (( ${#total_updates[@]} == 0 )); then
-        printf '%s\n' " ${r}No available update."
+        printf '%s\n' " ${R}No available update.${N}"
         read -r -t 3
         return 0
     else
         nl "$arch_aur_list"
-        printf '\n%s\n' " ${g}Available update(s): ${#total_updates[@]}${nc}"
+        printf '\n%s\n' " ${G}Available update(s): ${#total_updates[@]}${N}"
 
         _YesNoPrompt " Proceed with installation?" || {
-            printf '%s\n' " bye..."
+            printf '%s\n' " ${R}bye...${N}"
             read -r -t 2
             return 0
         }
 
+        for update in "${total_updates[@]}"; do
+            # shellcheck disable=SC2076
+            [[ $update =~ "$cachyos_mirr" || $update =~ "$chaotic_mirr" ]] && {
+                printf '%s\n' " ${G}rating $update, please be patient.${N}"
+                _rateMirrors third-party
+                break
+            }
+        done
+
         # first aur_list packages update
-        mapfile -t aur_packages < "$aur_list"
-        if (( ${#aur_packages[@]} > 0 )); then
-            yay -Sua
-            rm -rf "$HOME"/.ccache
-            if (( ${#aur_packages[@]} == ${#total_updates[@]} )); then
+        if (( ${#aur_updates[@]} > 0 )); then
+            _YesNoPrompt -n " ${R}Are you sure you want to upgrade AUR packages?${N}" || {
+                aur_updated=no
+                (( ${#arch_updates[@]} > 0 )) && _CheckReboot
+            }
+            for pkg in "${aur_updates[@]}"; do
+                [[ $pkg =~ yay ]] && yay -S yay-bin
+            done
+            yay -Sua --useask && rm -rf "$HOME"/.ccache
+            if (( ${#aur_updates[@]} == ${#total_updates[@]} )); then
                 sed -i '1,$d' {"$aur_list","$arch_aur_list"}
                 _PolybarHook
                 return 0
@@ -241,18 +309,37 @@ _ListUpdates() {
         fi
 
         # then Arch...
-        mapfile -t arch_packages < "$arch_list"
-        (( ${#arch_packages[@]} > 0 )) && _CheckReboot
+        [[ $aur_updated != "no" ]] && (( ${#arch_updates[@]} > 0 )) && _CheckReboot
 
     fi
 
 }
 
-case "$1" in
-    --chck) [[ -f $arch_aur_list ]] || _CheckUpdates ;;
+# In case we want to relaunch _CheckUpdates function,
+# or on the session startup.
+_CheckForRepoFiles() {
+
+    if [[ -f $arch_aur_list ]]; then
+        printf '%s\n' " ${R}${updates-manager##*/} is already running,"
+        _YesNoPrompt -n " Restart ${updates-manager##*/}?${N}" || return 1
+        rm {"$arch_list","$aur_list","$arch_aur_list"}
+        sleep 1
+        touch "$arch_aur_list"
+        return 0
+    else
+        touch "$arch_aur_list"
+        return 0
+    fi
+
+}
+
+# we can check and rate third party repos time to time using --rate third-party.
+case $1 in
+    --chck) _CheckForRepoFiles && _CheckUpdates ;;
     --hook) _PolybarHook ;;
     --list) _ListUpdates ;;
+    --rate) _rateMirrors "$2" ;; # official, third-party
     --snap) _AskforSnapshot && _Snapshot ;;
-    --stop) exit ;;
+    --stop) [[ -f $arch_aur_list ]] && _Cleanup ;;
     *     ) _Error "Wrong option: $1" 1 ;;
 esac
