screencaster: added -f option for audio filters

diff --git a/scripts/various/screencaster b/scripts/various/screencaster
--- a/scripts/various/screencaster
+++ b/scripts/various/screencaster
@@ -10,8 +10,10 @@
 # screencaster -m HDMI-A-0 -a alsa_output.pci-0000_0a_00.4.analog-stereo.monitor
 # If -m or -a is not provided, we will be prompt to set those required parameters.
 # See the _Usage function for more options/info.
+# You can also check the filters parameters and change them in the FILTERS array.
 
 # shellcheck disable=SC2140
+
 reset
 declare -a dependencies=(
     ffmpeg
@@ -27,6 +29,9 @@ for dependency in "${dependencies[@]}"; do
     }
 done
 
+grn=$'\e[32m';
+red=$'\e[31m';
+nc=$'\e[0m';
 now=$(date +%Y-%m-%d_%H:%M:%S)
 
 _Usage() {
@@ -36,25 +41,27 @@ _Usage() {
     " -b <yes/no>        Activate polybar mic/volume modules (default:no)" \
     " -d <audio delay>   If needed, to sync audio/video in milliseconds (default:0)" \
     " -D <add decibells> Number of decibells to add for the final result (default:1)" \
+    " -f <audio filter>  compressor, denoiser, cutfreq (one filter only)" \
     " -l <length>        How long the screencast should last (format = HH:MM:SS)" \
     " -m <monitor name>  example: HDMI-A-0 (required!)" \
     " -o <filename>      Output file (default:$HOME/screencast_$now.mkv)" \
     " -p <preset ratio>  Set the video quality (default:veryfast)" \
     " -r <resolution>    Set the screen resolution (default:1920x1080)" \
     " -v <volume>        Set the audio source level (in percentage) using pactl (default:80)"
-    echo -e "\n Currently available audio sources:\n"
+    echo -e "\n ${grn}Currently available audio sources:\n${nc}"
     pactl list sources short | awk '{print "  "$2}'
     exit 1
 }
 
 [[ $# -eq 0 ]] && _Usage
 # Parsing arguments
-while getopts "a:b:d:D:l:m:o:p:r:v:" opt; do
+while getopts "a:b:d:D:f:l:m:o:p:r:v:" opt; do
     case $opt in
         a) audio_source="${OPTARG}" ;;
         b) bar="${OPTARG}" ;;
         d) audio_delay="${OPTARG}" ;;
         D) ndB="${OPTARG}" ;;
+        f) filter="${OPTARG}" ;;
         l) length="${OPTARG}" ;;
         m) monitor="${OPTARG}" ;;
         o) output_file="${OPTARG}" ;;
@@ -67,6 +74,14 @@ done
 
 shift $((OPTIND - 1))
 
+# Change these parameters to your likings.
+# FFT-based (denoiser filter in dB)
+declare -A FILTERS=(
+    [compressor]="acompressor=threshold=-21dB:ratio=9:attack=200:release=1000"
+    [cutfreq]="highpass=200,lowpass=5000"
+    [denoiser]="afftdn=nf=-25"
+)
+
 # Default values
 audio_delay=${audio_delay:-0}
 bar=${bar:-no}
@@ -76,10 +91,22 @@ preset=${preset:-veryfast}
 resolution=${resolution:-"1920x1080"}
 volume=${volume:-80}
 
+# Validate filter if provided
+if [[ -n $filter ]]; then
+    if [[ -z ${FILTERS[$filter]} ]]; then
+        echo " ${red}Invalid filter: $filter${nc}"
+        echo " Available filters: ${grn}${!FILTERS[*]}${nc}"
+        exit 1
+    fi
+    filter=${FILTERS[$filter]}
+else
+    filter=""
+fi
+
 # Giving a menu for monitor choice if not provided
 [[ -z $monitor ]] && {
     printf '\n'
-    PS3=""$'\n'" Select a monitor: "
+    PS3=""$'\n'" ${grn}Select a monitor: ${nc}"
     select m in $(xrandr --listactivemonitors | awk '$0 !~ /Monitor/{print $NF}'); do
         if [[ -n ${m+x} ]]; then
             monitor="$m"
@@ -90,10 +117,10 @@ volume=${volume:-80}
     done
 }
 
-# ...and for audio source device
+# ...and for audio source device too.
 [[ -z $audio_source ]] && {
     printf '\n'
-    PS3=""$'\n'" Select an audio source: "
+    PS3=""$'\n'" ${grn}Select an audio source: ${nc}"
     select a in $(pactl list sources short | awk '{print "  "$2}'); do
         if [[ -n ${a+x} ]]; then
             audio_source="$a"
@@ -132,9 +159,9 @@ _SetInputVolume() { pactl set-source-volume @DEFAULT_SOURCE@ "$1"; }
 _SetOutputVolume() { pactl set-sink-volume @DEFAULT_SINK@ "$1"; }
 # Getting the current volume level so we can restore it when stopping the recording
 read -r currentvolume < <(
-        pactl get-sink-volume @DEFAULT_SINK@ \
-        | awk '{if(NR!=2) {print $5}}'
-    )
+    pactl get-sink-volume @DEFAULT_SINK@ \
+    | awk '{if(NR!=2) {print $5}}'
+)
 
 _SetVolume() {
     case "$1" in
@@ -180,29 +207,6 @@ _SetVolume() {
 
 [[ -n $volume ]] && _SetVolume on
 
-_TimeConverter() {
-    IFS=":";
-    if [[ $1  =~ ^[0-9]{2}:[0-9]{2}$ ]]; then
-        read -r minutes seconds <<< "$1"
-        total_seconds=$((minutes * 60 + seconds))
-    elif [[ $1  =~ ^[0-9]{2}:[0-9]{2}:[0-9]{2}$ ]]; then
-        read -r hours minutes seconds <<< "$1"
-        total_seconds=$(((hours * 3600) + (minutes * 60 + seconds)))
-    else
-        unset IFS
-        printf '\n%s\n' " Wrong duration format..."
-        _Usage
-    fi
-    unset IFS
-}
-
-[[ -n $length ]] && {
-    _TimeConverter "$length"
-    for ((i=1;i<="$total_seconds";i++)); do
-        sleep 1
-        (( i == total_seconds )) && killall --quiet ffmpeg
-    done &
-}
 
 # Get monitor position (xrandr output)
 monitor_position=$(
@@ -214,17 +218,53 @@ monitor_position=$(
 )
 
 if [[ -z $monitor_position ]]; then
-    echo "Could not determine monitor position for $monitor"
+    echo " ${red}Could not determine monitor position for $monitor${nc}"
     exit 1
 fi
 
 x=${monitor_position%,*}
 y=${monitor_position#*,}
 
-# FFT-based denoiser filter in dB
-# denoiser="afftdn=nf=-20"
-# cutfreq="highpass=200,lowpass=4000"
-compressor="acompressor=threshold=-21dB:ratio=9:attack=200:release=1000"
+_EndScreencast() {
+    [[ -n $volume ]] && _SetVolume off
+    reset
+    notify-send 'screencast is over'
+    exit 0
+}
+
+_TimeConverter() {
+    IFS=":";
+    if [[ $1  =~ ^[0-9]{2}:[0-9]{2}$ ]]; then
+        read -r minutes seconds <<< "$1"
+        total_seconds=$((minutes * 60 + seconds))
+    elif [[ $1  =~ ^[0-9]{2}:[0-9]{2}:[0-9]{2}$ ]]; then
+        read -r hours minutes seconds <<< "$1"
+        total_seconds=$(((hours * 3600) + (minutes * 60 + seconds)))
+    else
+        unset IFS
+        printf '\n%s\n' " ${red}Wrong duration format...${nc}"
+        _Usage
+    fi
+    unset IFS
+}
+
+[[ -n $length ]] && {
+    _TimeConverter "$length" && sleep 0.2
+    # Start a background timer process and save its PID
+    (
+        for ((i=1;i<="$total_seconds";i++)); do
+            sleep 1
+            (( i == total_seconds )) && {
+                kill -TERM "$(pidof ffmpeg)"
+                _EndScreencast
+            }
+        done
+    ) &
+    timer_pid=$!
+
+    # Trap SIGINT/SIGTERM to kill both ffmpeg and the timer process
+    trap 'kill -TERM "$(pidof ffmpeg)" "$timer_pid"; _EndScreencast' SIGINT SIGTERM
+}
 
 ffmpeg \
     -y \
@@ -234,7 +274,8 @@ ffmpeg \
     -f x11grab -i :0.0+"$x","$y" \
     -thread_queue_size 512 \
     -f pulse -i "$audio_source" \
-    -af "adelay=${audio_delay}|${audio_delay}",volume="$ndB"dB,"$compressor" \
+    -af "${audio_delay:+adelay=${audio_delay}|${audio_delay}}${audio_delay:+,}\
+        volume=${ndB}dB${filter:+,}${filter}" \
     -c:v libx264 \
     -preset "$preset" \
     -crf 23 \
@@ -244,7 +285,4 @@ ffmpeg \
     -fps_mode cfr \
     "$output_file"
 
-[[ -n $volume ]] && _SetVolume off
-reset
-notify-send -u critical 'screencast is over'
-exit 0
+_EndScreencast
