Update vim_conf

diff --git a/scripts/various/vim_conf b/scripts/various/vim_conf
--- a/scripts/various/vim_conf
+++ b/scripts/various/vim_conf
@@ -1,9 +1,8 @@
 #!/bin/bash
 
-# Dependency: awk, gawk or nawk, vim (set as VISUAL)
 confdir="$HOME/.config/CONFIGS"
 
-[ -d "$confdir" ] && cd "$confdir" || exit 1
+cd "$confdir" || exit 1
 
 PS3="Enter a file number to Edit or Remove (^C to exit): "
 
@@ -12,18 +11,19 @@ select link in $(find $confdir -type l | sort -d | sed 's,.*/,,'); do
     echo "[E]dit or [R]emove $link?:"
     read action
     case "$action" in
-        E|e) $VISUAL "$link" && break
+        E|e) $VISUAL "$link"
         ;;
         R|r) echo "Do you really want to REMOVE $link? [y/N]:"
             read del
             case $del in
-                y|yes|Y) rm "$link" && break
+                y|yes|Y) rm "$link"
                 ;;
-                n|no|N) echo "Deletion aborted" && break
+                n|no|N) echo "Deletion aborted"
                 ;;
                 *) echo "Unknown option...deletion aborted" && exit 1
                 ;;
             esac
         ;;
     esac
+    break
 done
